/* -*- Mode:Prolog; coding:utf-8; -*- */
%% Generated by regtopToBusTUC.VersionUpdate.java on 2018-08-13 10:02:42.292
%% FILE version.pl
%% SYSTEM TUC
%% CREATED TA-970913
/* REVISED : RS- */  version_date('AtB-I  Date 180813  Høst 2018').

%% Høst 2018
