/* -*- Mode:Prolog; coding:utf-8; -*- */
%% Generated by class GTFS_ToBussTUC on 2021-03-15 03:03:28.538
%% FILE version.pl
%% SYSTEM TUC
%% CREATED TA-970913
/* REVISED : AE- */  version_date('AtB-I Automatic update, updated on 2021-03-15 03:03:28.538').

%% Automatic update
