%% Generated by regtopToBusTUC.RegpasHolder.java on 2012-01-21 01:20:24.456

%% PASSES4 (TOURTYPE, STATION_NR, STATION, SEQ_NR, ARR_DELAY, DEP_DELAY)
%%    Example: passes4(17326,16011035,anton_grevskotts_vei,22,15,16).

%% NTOURSTOPS (TOURTYPE,LENGTH). Tourtype almost matches the linenumber in regpas.pl and FILE.TDA or FILE.TMS
%%    Defines the length (number of stations) inthe tourtype, e.g. ntourstops(12713,5).


%% PASSES4 (TOURTYPE, STATION NUMBER, STATION, SEQNUMBER, ARR DELAY, DEP DELAY)
passes4(1,16010718,st_olavs_gate,1,999,0).
passes4(1,16010719,dronningensgt,2,0,0).
passes4(1,16010724,hospitalkirka,3,1,1).
passes4(1,16010779,kalvskinnet,4,2,2).
passes4(1,16010715,skansen,5,3,3).
passes4(1,16010792,ila,6,4,4).
passes4(1,16010713,bergsli_gate,7,5,5).
passes4(1,16010712,nyveibakken_trondheim,8,6,6).
passes4(1,16010711,bygrensen,9,7,7).
passes4(1,16010740,belvedere,10,8,8).
passes4(1,16019999,breidablikk,11,9,9).
passes4(1,16010709,nordre_hoem,12,10,10).
passes4(1,16010708,søndre_hoem,13,11,11).
passes4(1,16010707,rognheim,14,13,13).
passes4(1,16010706,munkvoll_trikk,15,15,15).
passes4(1,16010705,ferstad,16,16,16).
passes4(1,16010704,ugla_trondheim,17,17,17).
passes4(1,16010703,kyvannet,18,18,18).
passes4(1,16010702,vestmarka,19,19,19).
passes4(1,16010701,herlofsenløypa,20,20,20).
passes4(1,16010700,lian_trondheim,21,21,999).
passes4(22,16010700,lian_trondheim,1,999,0).
passes4(22,16010701,herlofsenløypa,2,1,1).
passes4(22,16011702,vestmarka,3,2,2).
passes4(22,16010703,kyvannet,4,4,4).
passes4(22,16011704,ugla_trondheim,5,5,5).
passes4(22,16010705,ferstad,6,6,6).
passes4(22,16010706,munkvoll_trikk,7,8,8).
passes4(22,16010707,rognheim,8,9,9).
passes4(22,16011708,søndre_hoem,9,10,10).
passes4(22,16010709,nordre_hoem,10,11,11).
passes4(22,16019999,breidablikk,11,13,13).
passes4(22,16010740,belvedere,12,14,14).
passes4(22,16010711,bygrensen,13,15,15).
passes4(22,16010712,nyveibakken_trondheim,14,16,16).
passes4(22,16011792,ila,15,17,17).
passes4(22,16011715,skansen,16,18,18).
passes4(22,16011779,kalvskinnet,17,19,19).
passes4(22,16011724,hospitalkirka,18,20,20).
ntourstops(1,21).
ntourstops(22,18).
