%% FILE regcompstr.pl
%% SYSTEM BussTUC
%% CREATED  Automatically initially
%% REVISED TA-091125

:- module( regcompstr, [ composite_road/3 
       ] ).

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

composite_road(anders,[estenstads,street],anders_estenstads_street). %% New %% TA-091125

composite_road(anders,[wigens,street],anders_wigens_street). %% New %% TA-091117

composite_road(ole,[aasveds,street],ole_aasveds_street). %% New %% TA-091030

composite_road(aaeng,[street],aaeng_street).
composite_road(aasmund,[vinjes,street],aasmund_vinjes_street).
composite_road(aasmund,[vinjes_street],aasmund_vinjes_street).
composite_road(aasta,[hansteens,street],aasta_hansteens_street).
composite_road(aasta,[hansteens_street],aasta_hansteens_street).
composite_road(abels,[street],abels_street).
composite_road(abelsborg,[street],abelsborg_street).
composite_road(ada,[arnfinsens,street],ada_arnfinsens_street).
composite_road(ada,[arnfinsens_street],ada_arnfinsens_street).
composite_road(adolf,[øiens,street],adolf_øiens_street).
composite_road(adolf,[øiens_street],adolf_øiens_street).
composite_road(aksel,[nilsens,street],aksel_nilsens_street).
composite_road(aksel,[nilsens_street],aksel_nilsens_street).
composite_road(albertine,[wærness,street],albertine_wærness_street).
composite_road(albertine,[wærness_street],albertine_wærness_street).
composite_road(alette,[beyers,street],alette_beyers_street).
composite_road(alette,[beyers_street],alette_beyers_street).
composite_road(alexander,[holst,street],alexander_holst_street).
composite_road(alexander,[holst_street],alexander_holst_street).
composite_road(alexander,[kiellands,street],alexander_kiellands_street).
composite_road(alexander,[kiellands_street],alexander_kiellands_street).
composite_road(alf,[godagers,street],alf_godagers_street).
composite_road(alf,[godagers_street],alf_godagers_street).
composite_road(alf,[johansens,street],alf_johansens_street).
composite_road(alf,[johansens_street],alf_johansens_street).
composite_road(alfheimsvingen,[],alfheimsvingen).
composite_road(alfred,[getz,street],alfred_getz_street).
composite_road(alfred,[getz_street],alfred_getz_street).
composite_road(alfred,[hess,street],alfred_hess_street).
composite_road(alfred,[hess_street],alfred_hess_street).
composite_road(alfred,[larsens,street],alfred_larsens_street).
composite_road(alfred,[larsens_street],alfred_larsens_street).
composite_road(alfred,[trønsdals,street],alfred_trønsdals_street).
composite_road(alfred,[trønsdals_street],alfred_trønsdals_street).
composite_road(alme,[street],alme_street).
composite_road(alv,[schiefloes,street],alv_schiefloes_street).
composite_road(alv,[schiefloes_street],alv_schiefloes_street).
composite_road(amalienborg,[street],amalienborg_street).
composite_road(amalienlyst,[],amalienlyst).
composite_road(amtmannssvingen,[],amtmannssvingen).
composite_road(an,[magritts,street],an_magritts_street).
composite_road(an,[magritts_street],an_magritts_street).
composite_road(anders,[buens,street],anders_buens_street).
composite_road(anders,[buens_street],anders_buens_street).
composite_road(anders,[haarstads,street],anders_haarstads_street).
composite_road(anders,[haarstads_street],anders_haarstads_street).
composite_road(anders,[hovdens,street],anders_hovdens_street).
composite_road(anders,[hovdens_street],anders_hovdens_street).
composite_road(anders,[liaklevs,street],anders_liaklevs_street).
composite_road(anders,[liaklevs_street],anders_liaklevs_street).
composite_road(anders,[reitans,street],anders_reitans_street).
composite_road(anders,[reitans_street],anders_reitans_street).
composite_road(anders,[søyseths,street],anders_søyseths_street).
composite_road(anders,[søyseths_street],anders_søyseths_street).
composite_road(anders,[tvereggens,street],anders_tvereggens_street).
composite_road(anders,[tvereggens_street],anders_tvereggens_street).
composite_road(andreas,[claussens,street],andreas_claussens_street).
composite_road(andreas,[claussens_street],andreas_claussens_street).
composite_road(andreas,[holms,street],andreas_holms_street).
composite_road(andreas,[holms_street],andreas_holms_street).
composite_road(angellhaugen,[],angellhaugen).
composite_road(angelltrøa,[hovedgård],angelltrøa_hovedgård).
composite_road(angelltrø,[street],angelltrø_street).
composite_road(ankers,[street],ankers_street).
composite_road(anne,[ekrens,street],anne_ekrens_street).
composite_road(anne,[ekrens_street],anne_ekrens_street).
composite_road(anton,[bergs,street],anton_bergs_street).
composite_road(anton,[bergs_street],anton_bergs_street).
composite_road(anton,[grevskotts,street],anton_grevskotts_street).
composite_road(anton,[grevskotts_street],anton_grevskotts_street).
composite_road(anton,[kalvaas,street],anton_kalvaas_street).
composite_road(anton,[kalvaas_street],anton_kalvaas_street).
composite_road(antonie,[løchens,street],antonie_løchens_street).
composite_road(antonie,[løchens_street],antonie_løchens_street).
composite_road(apotekerveita,[],apotekerveita).
composite_road(arilds,[street],arilds_street).
composite_road(arkitekt,[christies,street],arkitekt_christies_street).
composite_road(arkitekt,[christies_street],arkitekt_christies_street).
composite_road(arkitekt,[ebbells,street],arkitekt_ebbells_street).
composite_road(arkitekt,[ebbells_street],arkitekt_ebbells_street).
composite_road(armauer,[hansens,street],armauer_hansens_street).
composite_road(armauer,[hansens_street],armauer_hansens_street).
composite_road(arne,[bergsgårds,street],arne_bergsgårds_street).
composite_road(arne,[bergsgårds_street],arne_bergsgårds_street).
composite_road(arne,[fjellbus,street],arne_fjellbus_street).
composite_road(arne,[fjellbus_street],arne_fjellbus_street).
composite_road(arne,[garborgs,street],arne_garborgs_street).
composite_road(arne,[garborgs_street],arne_garborgs_street).
composite_road(arne,[solbergs,street],arne_solbergs_street).
composite_road(arne,[solbergs_street],arne_solbergs_street).
composite_road(arneby,[street],arneby_street).
composite_road(arnt,[forseths,street],arnt_forseths_street).
composite_road(arnt,[forseths_street],arnt_forseths_street).
composite_road(arnt,[smistads,street],arnt_smistads_street).
composite_road(arnt,[smistads_street],arnt_smistads_street).
composite_road(asal,[street],asal_street).
composite_road(asbjørn,[øverås,street],asbjørn_øverås_street).
composite_road(asbjørn,[øverås_street],asbjørn_øverås_street).
composite_road(asbjørnsens,[street],asbjørnsens_street).
composite_road(askeladd,[street],askeladd_street).
composite_road(askgrobakken,[],askgrobakken).
composite_road(aslak,[bolts,street],aslak_bolts_street).
composite_road(aslak,[bolts_street],aslak_bolts_street).
composite_road(asp,[street],asp_street).
composite_road(astri,[aasens,street],astri_aasens_street).
composite_road(astri,[aasens_street],astri_aasens_street).
composite_road(astronom,[street],astronom_street).
composite_road(asylbakken,[],asylbakken).
composite_road(asylveita,[],asylveita).
composite_road(aunegrenda,[],aunegrenda).
composite_road(aune,[street],aune_street).
composite_road(austflata,[],austflata).
composite_road(baard,[iversens,street],baard_iversens_street).
composite_road(baard,[iversens_street],baard_iversens_street).
composite_road(bagler,[street],bagler_street).
composite_road(bakkaune,[street],bakkaune_street).
composite_road(bakke,[street],bakke_street).
composite_road(bakkehellet,[],bakkehellet).
composite_road(baldershage,[],baldershage).
composite_road(balders,[street],balders_street).
composite_road(batteri,[street],batteri_street).
composite_road(batteriveita,[],batteriveita).
composite_road(bauta,[street],bauta_street).
composite_road(bekkasin,[street],bekkasin_street).
composite_road(bekkefaret,[],bekkefaret).
composite_road(bekk,[street],bekk_street).
composite_road(belbu,[street],belbu_street).
composite_road(belvedere,[],belvedere).
composite_road(benneches,[street],benneches_street).
composite_road(bergheim,[street],bergheim_street).
composite_road(bergitta,[street],bergitta_street).
composite_road(bergljots,[street],bergljots_street).
composite_road(bergmester,[bachkes,street],bergmester_bachkes_street).
composite_road(bergmester,[bachkes_street],bergmester_bachkes_street).
composite_road(bergsbakken,[],bergsbakken).
composite_road(bergsli,[street],bergsli_street).
composite_road(bergstien,[],bergstien).
composite_road(bergtun,[street],bergtun_street).
composite_road(bernhard,[getz,street],bernhard_getz_street).
composite_road(bernhard,[getz_street],bernhard_getz_street).
composite_road(bernt,[lies,street],bernt_lies_street).
composite_road(bernt,[lies_street],bernt_lies_street).
composite_road(bersvendveita,[],bersvendveita).
composite_road(betemarka,[],betemarka).
composite_road(birkebeiner,[street],birkebeiner_street).
composite_road(biskop,[darres,street],biskop_darres_street).
composite_road(biskop,[darres_street],biskop_darres_street).
composite_road(biskop,[grimkjells,street],biskop_grimkjells_street).
composite_road(biskop,[grimkjells_street],biskop_grimkjells_street).
composite_road(biskop,[sigurds,street],biskop_sigurds_street).
composite_road(biskop,[sigurds_street],biskop_sigurds_street).
composite_road(biskop,[skaars,street],biskop_skaars_street).
composite_road(biskop,[skaars_street],biskop_skaars_street).
composite_road(bispe,[street],bispe_street).
composite_road(bissmiet,[],bissmiet).
composite_road(bjarne,[ness,street],bjarne_ness_street).
composite_road(bjarne,[ness_street],bjarne_ness_street).
composite_road(bjørkhaug,[street],bjørkhaug_street).
composite_road(bjørk,[street],bjørk_street).
composite_road(bjørndalen,[],bjørndalen).
composite_road(bjørneby,[street],bjørneby_street).
composite_road(bjørnsons,[street],bjørnsons_street).
composite_road(blaklieggen,[],blaklieggen).
composite_road(blaklihøgda,[],blaklihøgda).
composite_road(blakli,[street],blakli_street).
composite_road(blusuvoll,[alle],blusuvoll_alle).
composite_road(blusuvollsbakken,[],blusuvollsbakken).
composite_road(blåklokke,[street],blåklokke_street).
composite_road(borchgrevinks,[street],borchgrevinks_street).
composite_road(borghild,[rottems,street],borghild_rottems_street).
composite_road(borghild,[rottems_street],borghild_rottems_street).
composite_road(bostad,[street],bostad_street).
composite_road(brage,[street],brage_street).
composite_road(bragstads,[street],bragstads_street).
composite_road(brandhaugveita,[],brandhaugveita).
composite_road(brannhaugen,[],brannhaugen).
composite_road(bratsberg,[street],bratsberg_street).
composite_road(brattvoll,[street],brattvoll_street).
composite_road(brattør,[street],brattør_street).
composite_road(brattørkaia,[],brattørkaia).
composite_road(brattøveita,[],brattøveita).
composite_road(bregne,[street],bregne_street).
composite_road(breidablikkstien,[],breidablikkstien).
composite_road(breidablik,[street],breidablik_street).
composite_road(breisyn,[street],breisyn_street).
composite_road(brian,[smiths,street],brian_smiths_street).
composite_road(brian,[smiths_street],brian_smiths_street).
composite_road(brinken,[],brinken).
composite_road(brodals,[street],brodals_street).
composite_road(broddes,[street],broddes_street).
composite_road(brodtkorbs,[street],brodtkorbs_street).
composite_road(bromstadbuen,[],bromstadbuen).
composite_road(bromstadekra,[],bromstadekra).
composite_road(bromstad,[street],bromstad_street).
composite_road(brubakken,[],brubakken).
composite_road(brudals,[street],brudals_street).
composite_road(brukseier,[olsens,street],brukseier_olsens_street).
composite_road(brukseier,[olsens_street],brukseier_olsens_street).
composite_road(brundalen,[],brundalen).
composite_road(brundalsgrenda,[],brundalsgrenda).
composite_road(brushane,[street],brushane_street).
composite_road(bryns,[street],bryns_street).
composite_road(brænnes,[street],brænnes_street).
composite_road(brøsetdalen,[],brøsetdalen).
composite_road(brøset,[street],brøset_street).
composite_road(brøttems,[street],brøttems_street).
composite_road(bråmyra,[],bråmyra).
composite_road(buckhaugen,[],buckhaugen).
composite_road(bueng,[street],bueng_street).
composite_road(bugges,[street],bugges_street).
composite_road(bukken,[bruses,street],bukken_bruses_street).
composite_road(bukken,[bruses_street],bukken_bruses_street).
composite_road(bukkvollan,[],bukkvollan).
composite_road(burslia,[],burslia).
composite_road(bynes,[street],bynes_street).
composite_road(byås,[street],byås_street).
composite_road(bøckmans,[street],bøckmans_street).
composite_road(bøk,[street],bøk_street).
composite_road(båhus,[street],båhus_street).
composite_road(c,[j,hambros,street],c_j_hambros_street).
composite_road(c,[j,hambros_street],c_j_hambros_street).
composite_road(camilla,[collets,street],camilla_collets_street).
composite_road(camilla,[collets_street],camilla_collets_street).
composite_road(carl,[dons,street],carl_dons_street).
composite_road(carl,[dons_street],carl_dons_street).
composite_road(carl,[johans,street],carl_johans_street).
composite_road(carl,[johans_street],carl_johans_street).
composite_road(carl,[lønseths,street],carl_lønseths_street).
composite_road(carl,[lønseths_street],carl_lønseths_street).
composite_road(carl,[schjetnans,street],carl_schjetnans_street).
composite_road(carl,[schjetnans_street],carl_schjetnans_street).
composite_road(carl,[w,lanssens,street],carl_w_lanssens_street).
composite_road(carl,[w,lanssens_street],carl_w_lanssens_street).
composite_road(casparis,[street],casparis_street).
composite_road(casper,[lundes,street],casper_lundes_street).
composite_road(casper,[lundes_street],casper_lundes_street).
composite_road(catharine,[lysholms,street],catharine_lysholms_street).
composite_road(catharine,[lysholms_street],catharine_lysholms_street).
composite_road(cecilie,[thoresens,street],cecilie_thoresens_street).
composite_road(cecilie,[thoresens_street],cecilie_thoresens_street).
composite_road(christian,[bloms,street],christian_bloms_street).
composite_road(christian,[bloms_street],christian_bloms_street).
composite_road(christian,[eggens,street],christian_eggens_street).
composite_road(christian,[eggens_street],christian_eggens_street).
composite_road(christian,[fredriks,street],christian_fredriks_street).
composite_road(christian,[fredriks_street],christian_fredriks_street).
composite_road(christian,[jelstrups,street],christian_jelstrups_street).
composite_road(christian,[jelstrups_street],christian_jelstrups_street).
composite_road(christian,[monsens,street],christian_monsens_street).
composite_road(christian,[monsens_street],christian_monsens_street).
composite_road(churchills,[street],churchills_street).
composite_road(cicilie,[street],cicilie_street).
composite_road(credoeveita,[],credoeveita).
composite_road(dalen,[hageby],dalen_hageby).
composite_road(dalgårdstien,[],dalgårdstien).
composite_road(dalhaug,[street],dalhaug_street).
composite_road(dalheimslyngen,[],dalheimslyngen).
composite_road(dalheim,[street],dalheim_street).
composite_road(dalkant,[street],dalkant_street).
composite_road(dalsaune,[street],dalsaune_street).
composite_road(dalstien,[],dalstien).
composite_road(danielsveita,[],danielsveita).
composite_road(devlesvingen,[],devlesvingen).
composite_road(dickaunesvingen,[],dickaunesvingen).
composite_road(dikehaugen,[],dikehaugen).
composite_road(distriktslege,[øverlids,street],distriktslege_øverlids_street).
composite_road(distriktslege,[øverlids_street],distriktslege_øverlids_street).
composite_road(ditlev,[bloms,street],ditlev_bloms_street).
composite_road(ditlev,[bloms_street],ditlev_bloms_street).
composite_road(dokk,[street],dokk_street).
composite_road(dr,[sands,street],dr_sands_street).
composite_road(dr,[sands_street],dr_sands_street).
composite_road(dragvoll,[alle],dragvoll_alle).
composite_road(drillveita,[],drillveita).
composite_road(dronning,[åsas,street],dronning_åsas_street).
composite_road(dronning,[åsas_street],dronning_åsas_street).
composite_road(dronningens,[street],dronningens_street).
composite_road(duelunden,[],duelunden).
composite_road(dvergstien,[],dvergstien).
composite_road(dybdahls,[street],dybdahls_street).
composite_road(dyrborg,[street],dyrborg_street).
composite_road(e,[c,dahls,street],e_c_dahls_street).
composite_road(e,[c,dahls_street],e_c_dahls_street).
composite_road(edgar,[b,schieldrops,street],edgar_b_schieldrops_street).
composite_road(edgar,[b,schieldrops_street],edgar_b_schieldrops_street).
composite_road(edvard,[griegs,street],edvard_griegs_street).
composite_road(edvard,[griegs_street],edvard_griegs_street).
composite_road(eggan,[street],eggan_street).
composite_road(eidsvolls,[street],eidsvolls_street).
composite_road(eik,[street],eik_street).
composite_road(eilert,[sundts,street],eilert_sundts_street).
composite_road(eilert,[sundts_street],eilert_sundts_street).
composite_road(eilif,[gulbransons,street],eilif_gulbransons_street).
composite_road(eilif,[gulbransons_street],eilif_gulbransons_street).
composite_road(einar,[solstads,street],einar_solstads_street).
composite_road(einar,[solstads_street],einar_solstads_street).
composite_road(einar,[tamberskjelves,street],einar_tamberskjelves_street).
composite_road(einar,[tamberskjelves_street],einar_tamberskjelves_street).
composite_road(einar,[øfstis,street],einar_øfstis_street).
composite_road(einar,[øfstis_street],einar_øfstis_street).
composite_road(einer,[street],einer_street).
composite_road(einmoen,[],einmoen).
composite_road(eirik,[jarls,street],eirik_jarls_street).
composite_road(eirik,[jarls_street],eirik_jarls_street).
composite_road(ekorn,[street],ekorn_street).
composite_road(elgeseter,[street],elgeseter_street).
composite_road(elg,[street],elg_street).
composite_road(eli,[sjursdotters,street],eli_sjursdotters_street).
composite_road(eli,[sjursdotters_street],eli_sjursdotters_street).
composite_road(ellefsens,[street],ellefsens_street).
composite_road(ellen,[lies,street],ellen_lies_street).
composite_road(ellen,[lies_street],ellen_lies_street).
composite_road(elve,[street],elve_street).
composite_road(emilie,[kroghs,street],emilie_kroghs_street).
composite_road(emilie,[kroghs_street],emilie_kroghs_street).
composite_road(engelsås,[street],engelsås_street).
composite_road(eng,[street],eng_street).
composite_road(enerom,[street],enerom_street).
composite_road(erika,[lies,street],erika_lies_street).
composite_road(erika,[lies_street],erika_lies_street).
composite_road(erlends,[street],erlends_street).
composite_road(erling,[høviks,street],erling_høviks_street).
composite_road(erling,[høviks_street],erling_høviks_street).
composite_road(erling,[skakkes,street],erling_skakkes_street).
composite_road(erling,[skakkes_street],erling_skakkes_street).
composite_road(erling,[skjalgssons,street],erling_skjalgssons_street).
composite_road(erling,[skjalgssons_street],erling_skjalgssons_street).
composite_road(esp,[street],esp_street).
composite_road(essendrops,[street],essendrops_street).
composite_road(estenstad,[street],estenstad_street).
composite_road(even,[lorengs,street],even_lorengs_street).
composite_road(even,[lorengs_street],even_lorengs_street).
composite_road(eventyr,[street],eventyr_street).
composite_road(eyvind,[løkkens,street],eyvind_løkkens_street).
composite_road(eyvind,[løkkens_street],eyvind_løkkens_street).
composite_road(fagerheim,[alle],fagerheim_alle).
composite_road(fagerli,[street],fagerli_street).
composite_road(fagertun,[street],fagertun_street).
composite_road(falsens,[street],falsens_street).
composite_road(fernanda,[nissens,street],fernanda_nissens_street).
composite_road(fernanda,[nissens_street],fernanda_nissens_street).
composite_road(ferstadbakken,[],ferstadbakken).
composite_road(festnings,[street],festnings_street).
composite_road(finn,[bergs,street],finn_bergs_street).
composite_road(finn,[bergs_street],finn_bergs_street).
composite_road(fiolsvingen,[],fiolsvingen).
composite_road(fjellseter,[street],fjellseter_street).
composite_road(fjordgløtt,[street],fjordgløtt_street).
composite_road(fjord,[street],fjord_street).
composite_road(fjære,[street],fjære_street).
composite_road(fjøslia,[],fjøslia).
composite_road(fjøsmester,[street],fjøsmester_street).
composite_road(flakkhaugen,[],flakkhaugen).
composite_road(flatåsenget,[],flatåsenget).
composite_road(flatåstoppen,[],flatåstoppen).
composite_road(fogdenget,[],fogdenget).
composite_road(forsøkslia,[],forsøkslia).
composite_road(fortuna,[street],fortuna_street).
composite_road(fortunalia,[],fortunalia).
composite_road(fosenkaia,[],fosenkaia).
composite_road(fossbakken,[],fossbakken).
composite_road(fossegrenda,[],fossegrenda).
composite_road(fossestu,[street],fossestu_street).
composite_road(fotveita,[],fotveita).
composite_road(fram,[street],fram_street).
composite_road(fredrik,[b,wallems,street],fredrik_b_wallems_street).
composite_road(fredrik,[b,wallems_street],fredrik_b_wallems_street).
composite_road(fredrik,[kolstøs,street],fredrik_kolstøs_street).
composite_road(fredrik,[kolstøs_street],fredrik_kolstøs_street).
composite_road(fredrikkested,[],fredrikkested).
composite_road(freidigstien,[],freidigstien).
composite_road(fridheim,[street],fridheim_street).
composite_road(friggs,[street],friggs_street).
composite_road(fritjof,[nansens,street],fritjof_nansens_street).
composite_road(fritjof,[nansens_street],fritjof_nansens_street).
composite_road(fritz,[aabakkens,street],fritz_aabakkens_street).
composite_road(fritz,[aabakkens_street],fritz_aabakkens_street).
composite_road(frode,[rinnans,street],frode_rinnans_street).
composite_road(frode,[rinnans_street],frode_rinnans_street).
composite_road(frosta,[street],frosta_street).
composite_road(frydenberg,[street],frydenberg_street).
composite_road(frøys,[street],frøys_street).
composite_road(furu,[street],furu_street).
composite_road(fyken,[street],fyken_street).
composite_road(gabriel,[scotts,street],gabriel_scotts_street).
composite_road(gabriel,[scotts_street],gabriel_scotts_street).
composite_road(gabriel,[vollans,street],gabriel_vollans_street).
composite_road(gabriel,[vollans_street],gabriel_vollans_street).
composite_road(gamle,[kirke,street],gamle_kirke_street).
composite_road(gamle,[kirke_street],gamle_kirke_street).
composite_road(gamle,[konge,street],gamle_konge_street).
composite_road(gamle,[konge_street],gamle_konge_street).
composite_road(gamle,[oslo,street],gamle_oslo_street).
composite_road(gamle,[oslo_street],gamle_oslo_street).
composite_road(gamle,[ås,street],gamle_ås_street).
composite_road(gamle,[ås_street],gamle_ås_street).
composite_road(gammel,[lina],gammel_lina).
composite_road(gardemoens,[street],gardemoens_street).
composite_road(garmanns,[street],garmanns_street).
composite_road(gartnerhaug,[street],gartnerhaug_street).
composite_road(gartneri,[street],gartneri_street).
composite_road(gaubekveita,[],gaubekveita).
composite_road(gaupe,[street],gaupe_street).
composite_road(gautes,[street],gautes_street).
composite_road(geelmuydens,[street],geelmuydens_street).
composite_road(general,[bangs,street],general_bangs_street).
composite_road(general,[bangs_street],general_bangs_street).
composite_road(general,[buddes,street],general_buddes_street).
composite_road(general,[buddes_street],general_buddes_street).
composite_road(general,[von,hovens,street],general_von_hovens_street).
composite_road(general,[von,hovens_street],general_von_hovens_street).
composite_road(general,[von,kroghs,street],general_von_kroghs_street).
composite_road(general,[von,kroghs_street],general_von_kroghs_street).
composite_road(general,[wibes,street],general_wibes_street).
composite_road(general,[wibes_street],general_wibes_street).
composite_road(gildheims,[street],gildheims_street).
composite_road(gimle,[street],gimle_street).
composite_road(gina,[krogs,street],gina_krogs_street).
composite_road(gina,[krogs_street],gina_krogs_street).
composite_road(gisle,[johnsons,street],gisle_johnsons_street).
composite_road(gisle,[johnsons_street],gisle_johnsons_street).
composite_road(gjelvangveita,[],gjelvangveita).
composite_road(gjerlovs,[street],gjerlovs_street).
composite_road(gjetveita,[],gjetveita).
composite_road(gjøa,[street],gjøa_street).
composite_road(gjørtler,[street],gjørtler_street).
composite_road(gløshaug,[street],gløshaug_street).
composite_road(gogstadbakken,[],gogstadbakken).
composite_road(granhaugan,[],granhaugan).
composite_road(granli,[street],granli_street).
composite_road(gran,[street],gran_street).
composite_road(granåslia,[],granåslia).
composite_road(granås,[street],granås_street).
composite_road(gregus,[street],gregus_street).
composite_road(grensen,[],grensen).
composite_road(gressbane,[street],gressbane_street).
composite_road(griffenfelds,[street],griffenfelds_street).
composite_road(grilstad,[street],grilstad_street).
composite_road(grova,[],grova).
composite_road(grundtvigs,[street],grundtvigs_street).
composite_road(gryta,[],gryta).
composite_road(grytbakkstranda,[],grytbakkstranda).
composite_road(grøndahls,[street],grøndahls_street).
composite_road(gråtrost,[street],gråtrost_street).
composite_road(gudes,[street],gudes_street).
composite_road(gudruns,[street],gudruns_street).
composite_road(guldbrands,[street],guldbrands_street).
composite_road(gulspurv,[street],gulspurv_street).
composite_road(gunnar,[birchs,street],gunnar_birchs_street).
composite_road(gunnar,[birchs_street],gunnar_birchs_street).
composite_road(gunnerus,[street],gunnerus_street).
composite_road(gunnlaugs,[street],gunnlaugs_street).
composite_road(gustav,[byes,street],gustav_byes_street).
composite_road(gustav,[byes_street],gustav_byes_street).
composite_road(guttorms,[street],guttorms_street).
composite_road(gyldenløves,[street],gyldenløves_street).
composite_road(haakon,[viis,street],haakon_viis_street).
composite_road(haakon,[viis_street],haakon_viis_street).
composite_road(haldens,[street],haldens_street).
composite_road(haldor,[flatens,street],haldor_flatens_street).
composite_road(haldor,[flatens_street],haldor_flatens_street).
composite_road(hallfred,[høyems,street],hallfred_høyems_street).
composite_road(hallfred,[høyems_street],hallfred_høyems_street).
composite_road(hallsetreina,[],hallsetreina).
composite_road(hammerverks,[street],hammerverks_street).
composite_road(hanna,[winsnes,street],hanna_winsnes_street).
composite_road(hanna,[winsnes_street],hanna_winsnes_street).
composite_road(hans,[aaneruds,street],hans_aaneruds_street).
composite_road(hans,[aaneruds_street],hans_aaneruds_street).
composite_road(hans,[barliens,street],hans_barliens_street).
composite_road(hans,[barliens_street],hans_barliens_street).
composite_road(hans,[baucks,street],hans_baucks_street).
composite_road(hans,[baucks_street],hans_baucks_street).
composite_road(hans,[bruns,street],hans_bruns_street).
composite_road(hans,[bruns_street],hans_bruns_street).
composite_road(hans,[collins,street],hans_collins_street).
composite_road(hans,[collins_street],hans_collins_street).
composite_road(hans,[finnes,street],hans_finnes_street).
composite_road(hans,[finnes_street],hans_finnes_street).
composite_road(hans,[hagerups,street],hans_hagerups_street).
composite_road(hans,[hagerups_street],hans_hagerups_street).
composite_road(hans,[michelsens,street],hans_michelsens_street).
composite_road(hans,[michelsens_street],hans_michelsens_street).
composite_road(hans,[nielsen,hauges,street],hans_nielsen_hauges_street).
composite_road(hans,[nielsen,hauges_street],hans_nielsen_hauges_street).
composite_road(hans,[nissens,street],hans_nissens_street).
composite_road(hans,[nissens_street],hans_nissens_street).
composite_road(hans,[osnes,street],hans_osnes_street).
composite_road(hans,[osnes_street],hans_osnes_street).
composite_road(hansbakken,[],hansbakken).
composite_road(hanskemakerbakken,[],hanskemakerbakken).
composite_road(harald,[bothners,street],harald_bothners_street).
composite_road(harald,[bothners_street],harald_bothners_street).
composite_road(harald,[gilles,street],harald_gilles_street).
composite_road(harald,[gilles_street],harald_gilles_street).
composite_road(harald,[hardrådes,street],harald_hardrådes_street).
composite_road(harald,[hardrådes_street],harald_hardrådes_street).
composite_road(harald,[hårfagres,street],harald_hårfagres_street).
composite_road(harald,[hårfagres_street],harald_hårfagres_street).
composite_road(harald,[langhelles,street],harald_langhelles_street).
composite_road(harald,[langhelles_street],harald_langhelles_street).
composite_road(harald,[samuelsens,street],harald_samuelsens_street).
composite_road(harald,[samuelsens_street],harald_samuelsens_street).
composite_road(hare,[street],hare_street).
composite_road(harry,[borthens,street],harry_borthens_street).
composite_road(harry,[borthens_street],harry_borthens_street).
composite_road(hasselbakk,[street],hasselbakk_street).
composite_road(haugnessvingen,[],haugnessvingen).
composite_road(haugstien,[],haugstien).
composite_road(hauglia,[],hauglia).
composite_road(havne,[street],havne_street).
composite_road(havre,[street],havre_street).
composite_road(havstad,[street],havstad_street).
composite_road(havsteinbakken,[],havsteinbakken).
composite_road(havsteinflata,[],havsteinflata).
composite_road(havsteinlia,[],havsteinlia).
composite_road(heggdalsringen,[],heggdalsringen).
composite_road(heggsnip,[street],heggsnip_street).
composite_road(heggstadmoen,[],heggstadmoen).
composite_road(heggstadmyra,[],heggstadmyra).
composite_road(hegg,[street],hegg_street).
composite_road(heimdals,[street],heimdals_street).
composite_road(heimstad,[street],heimstad_street).
composite_road(heimtrøa,[],heimtrøa).
composite_road(heimtun,[],heimtun).
composite_road(helmer,[hanssens,street],helmer_hanssens_street).
composite_road(helmer,[hanssens_street],helmer_hanssens_street).
composite_road(helmer,[lundgrens,street],helmer_lundgrens_street).
composite_road(helmer,[lundgrens_street],helmer_lundgrens_street).
composite_road(henrik,[angells,street],henrik_angells_street).
composite_road(henrik,[angells_street],henrik_angells_street).
composite_road(henrik,[mathiesens,street],henrik_mathiesens_street).
composite_road(henrik,[mathiesens_street],henrik_mathiesens_street).
composite_road(henrik,[ourens,street],henrik_ourens_street).
composite_road(henrik,[ourens_street],henrik_ourens_street).
composite_road(henry,[gleditsch,street],henry_gleditsch_street).
composite_road(henry,[gleditsch_street],henry_gleditsch_street).
composite_road(henry,[thingstads,street],henry_thingstads_street).
composite_road(henry,[thingstads_street],henry_thingstads_street).
composite_road(herlofsons,[street],herlofsons_street).
composite_road(herman,[krags,street],herman_krags_street).
composite_road(herman,[krags_street],herman_krags_street).
composite_road(hirsch,[komissars,street],hirsch_komissars_street).
composite_road(hirsch,[komissars_street],hirsch_komissars_street).
composite_road(hitra,[street],hitra_street).
composite_road(hjalmar,[haalkes,street],hjalmar_haalkes_street).
composite_road(hjalmar,[haalkes_street],hjalmar_haalkes_street).
composite_road(hjalmar,[johansens,street],hjalmar_johansens_street).
composite_road(hjalmar,[johansens_street],hjalmar_johansens_street).
composite_road(hoegg,[street],hoegg_street).
composite_road(hoemsbakken,[],hoemsbakken).
composite_road(hoemshøgda,[],hoemshøgda).
composite_road(hoems,[street],hoems_street).
composite_road(lars,[hofstads,street],lars_hofstads_street).
composite_road(lars,[hofstads_street],lars_hofstads_street).
composite_road(holbergs,[street],holbergs_street).
composite_road(holstveita,[],holstveita).
composite_road(holtermanns,[street],holtermanns_street).
composite_road(holt,[street],holt_street).
composite_road(horneberg,[street],horneberg_street).
composite_road(hospitals,[street],hospitals_street).
composite_road(hospitalsløkkan,[],hospitalsløkkan).
composite_road(hugins,[street],hugins_street).
composite_road(hulder,[street],hulder_street).
composite_road(humlehaug,[street],humlehaug_street).
composite_road(husebyhøgda,[],husebyhøgda).
composite_road(huseby,[street],huseby_street).
composite_road(hvedingsveita,[],hvedingsveita).
composite_road(hyll,[street],hyll_street).
composite_road(høgreina,[],høgreina).
composite_road(høgsetgrenda,[],høgsetgrenda).
composite_road(høgskoleringen,[],høgskoleringen).
composite_road(høgskole,[street],høgskole_street).
composite_road(høili,[plass],høili_plass).
composite_road(høili,[street],høili_street).
composite_road(hølbekken,[],hølbekken).
composite_road(hørløcks,[street],hørløcks_street).
composite_road(håkon,[herdebreis,street],håkon_herdebreis_street).
composite_road(håkon,[herdebreis_street],håkon_herdebreis_street).
composite_road(håkon,[håkonsons,street],håkon_håkonsons_street).
composite_road(håkon,[håkonsons_street],håkon_håkonsons_street).
composite_road(håkon,[jarls,street],håkon_jarls_street).
composite_road(håkon,[jarls_street],håkon_jarls_street).
composite_road(håkon,[magnussons,street],håkon_magnussons_street).
composite_road(håkon,[magnussons_street],håkon_magnussons_street).
composite_road(håkon,[sverressons,street],håkon_sverressons_street).
composite_road(håkon,[sverressons_street],håkon_sverressons_street).
composite_road(hårstadstien,[],hårstadstien).
composite_road(ibsens,[street],ibsens_street).
composite_road(idretts,[street],idretts_street).
composite_road(iduns,[street],iduns_street).
composite_road(ilevollen,[],ilevollen).
composite_road(ilsvik,[street],ilsvik_street).
composite_road(ilsvikøra,[],ilsvikøra).
composite_road(industri,[street],industri_street).
composite_road(ingemann,[torps,street],ingemann_torps_street).
composite_road(ingemann,[torps_street],ingemann_torps_street).
composite_road(inge,[krokanns,street],inge_krokanns_street).
composite_road(inge,[krokanns_street],inge_krokanns_street).
composite_road(ingeborg,[aas,street],ingeborg_aas_street).
composite_road(ingeborg,[aas_street],ingeborg_aas_street).
composite_road(ingrid,[kiærs,street],ingrid_kiærs_street).
composite_road(ingrid,[kiærs_street],ingrid_kiærs_street).
composite_road(ingvald,[undsets,street],ingvald_undsets_street).
composite_road(ingvald,[undsets_street],ingvald_undsets_street).
composite_road(ingvald,[ystgaards,street],ingvald_ystgaards_street).
composite_road(ingvald,[ystgaards_street],ingvald_ystgaards_street).
composite_road(innbrektsflata,[],innbrektsflata).
composite_road(innherreds,[street],innherreds_street).
composite_road(ivar,[lykkes,street],ivar_lykkes_street).
composite_road(ivar,[lykkes_street],ivar_lykkes_street).
composite_road(iver,[trøans,street],iver_trøans_street).
composite_road(iver,[trøans_street],iver_trøans_street).
composite_road(ivar,[aasens,street],ivar_aasens_street).
composite_road(ivar,[aasens_street],ivar_aasens_street).
composite_road(ivar,[mortensons,street],ivar_mortensons_street).
composite_road(ivar,[mortensons_street],ivar_mortensons_street).
composite_road(j,[o,stavs,street],j_o_stavs_street).
composite_road(j,[o,stavs_street],j_o_stavs_street).
composite_road(jacob,[b,bulls,street],jacob_b_bulls_street).
composite_road(jacob,[b,bulls_street],jacob_b_bulls_street).
composite_road(jacob,[rolls,street],jacob_rolls_street).
composite_road(jacob,[rolls_street],jacob_rolls_street).
composite_road(jakob,[kjeviks,street],jakob_kjeviks_street).
composite_road(jakob,[kjeviks_street],jakob_kjeviks_street).
composite_road(jakobsli,[street],jakobsli_street).
composite_road(jakobstien,[],jakobstien).
composite_road(jarle,[street],jarle_street).
composite_road(jarlheimbakken,[],jarlheimbakken).
composite_road(jarlsborg,[street],jarlsborg_street).
composite_road(jar,[street],jar_street).
composite_road(jebe,[street],jebe_street).
composite_road(jens,[tvedts,street],jens_tvedts_street).
composite_road(jens,[tvedts_street],jens_tvedts_street).
composite_road(jernbane,[street],jernbane_street).
composite_road(jo,[lias,street],jo_lias_street).
composite_road(jo,[lias_street],jo_lias_street).
composite_road(johan,[bojers,street],johan_bojers_street).
composite_road(johan,[bojers_street],johan_bojers_street).
composite_road(johan,[cappelens,street],johan_cappelens_street).
composite_road(johan,[cappelens_street],johan_cappelens_street).
composite_road(johan,[e,brodahls,street],johan_e_brodahls_street).
composite_road(johan,[e,brodahls_street],johan_e_brodahls_street).
composite_road(johan,[falkbergets,street],johan_falkbergets_street).
composite_road(johan,[falkbergets_street],johan_falkbergets_street).
composite_road(johan,[nygaardsvolds,street],johan_nygaardsvolds_street).
composite_road(johan,[nygaardsvolds_street],johan_nygaardsvolds_street).
composite_road(johan,[svendsens,street],johan_svendsens_street).
composite_road(johan,[svendsens_street],johan_svendsens_street).
composite_road(johan,[tillers,street],johan_tillers_street).
composite_road(johan,[tillers_street],johan_tillers_street).
composite_road(johannes,[minsaas,street],johannes_minsaas_street).
composite_road(johannes,[minsaas_street],johannes_minsaas_street).
composite_road(john,[bjørgums,street],john_bjørgums_street).
composite_road(john,[bjørgums_street],john_bjørgums_street).
composite_road(john,[p,kroglunds,street],john_p_kroglunds_street).
composite_road(john,[p,kroglunds_street],john_p_kroglunds_street).
composite_road(john,[skaarvolds,street],john_skaarvolds_street).
composite_road(john,[skaarvolds_street],john_skaarvolds_street).
composite_road(john,[solems,street],john_solems_street).
composite_road(john,[solems_street],john_solems_street).
composite_road(johnny,[peviks,street],johnny_peviks_street).
composite_road(johnny,[peviks_street],johnny_peviks_street).
composite_road(jomfru,[street],jomfru_street).
composite_road(jon,[raudes,street],jon_raudes_street).
composite_road(jon,[raudes_street],jon_raudes_street).
composite_road(jon,[sivertsens,street],jon_sivertsens_street).
composite_road(jon,[sivertsens_street],jon_sivertsens_street).
composite_road(jon,[skogstads,street],jon_skogstads_street).
composite_road(jon,[skogstads_street],jon_skogstads_street).
composite_road(jonas,[lies,street],jonas_lies_street).
composite_road(jonas,[lies_street],jonas_lies_street).
composite_road(jonsvanns,[street],jonsvanns_street).
composite_road(jotun,[street],jotun_street).
composite_road(jupiter,[street],jupiter_street).
composite_road(jørgen,[b,lysholms,street],jørgen_b_lysholms_street).
composite_road(jørgen,[b,lysholms_street],jørgen_b_lysholms_street).
composite_road(jørgen,[bjelkes,street],jørgen_bjelkes_street).
composite_road(jørgen,[bjelkes_street],jørgen_bjelkes_street).
composite_road(jørgen,[hegstads,street],jørgen_hegstads_street).
composite_road(jørgen,[hegstads_street],jørgen_hegstads_street).
composite_road(jørgen,[moes,street],jørgen_moes_street).
composite_road(jørgen,[moes_street],jørgen_moes_street).
composite_road(jørunds,[street],jørunds_street).
composite_road(k,[o,thornæs,street],k_o_thornæs_street).
composite_road(k,[o,thornæs_street],k_o_thornæs_street).
composite_road(kalvskinns,[street],kalvskinns_street).
composite_road(kammen,[],kammen).
composite_road(kannikesetrete,[],kannikesetrete).
composite_road(kaptein,[kaalds,street],kaptein_kaalds_street).
composite_road(kaptein,[kaalds_street],kaptein_kaalds_street).
composite_road(kaptein,[mitlids,street],kaptein_mitlids_street).
composite_road(kaptein,[mitlids_street],kaptein_mitlids_street).
composite_road(kaptein,[roosens,street],kaptein_roosens_street).
composite_road(kaptein,[roosens_street],kaptein_roosens_street).
composite_road(karen,[blekkans,street],karen_blekkans_street).
composite_road(karen,[blekkans_street],karen_blekkans_street).
composite_road(karisvingen,[],karisvingen).
composite_road(karl,[jonssons,street],karl_jonssons_street).
composite_road(karl,[jonssons_street],karl_jonssons_street).
composite_road(karoliner,[street],karoliner_street).
composite_road(karse,[street],karse_street).
composite_road(kattemskogen,[],kattemskogen).
composite_road(kattems,[street],kattems_street).
composite_road(kirke,[street],kirke_street).
composite_road(kirkeringen,[],kirkeringen).
composite_road(kirkvollen,[],kirkvollen).
composite_road(kjøpmanns,[street],kjøpmanns_street).
composite_road(klefstadhaugen,[],klefstadhaugen).
composite_road(kleists,[street],kleists_street).
composite_road(kleiva,[street],kleiva_street).
composite_road(klett,[street],klett_street).
composite_road(klingenbergs,[street],klingenbergs_street).
composite_road(klokker,[lassens,street],klokker_lassens_street).
composite_road(klokker,[lassens_street],klokker_lassens_street).
composite_road(klokkstein,[street],klokkstein_street).
composite_road(klosterenget,[],klosterenget).
composite_road(kloster,[street],kloster_street).
composite_road(kluwers,[street],kluwers_street).
composite_road(klæbu,[street],klæbu_street).
composite_road(kløver,[street],kløver_street).
composite_road(knudssøns,[street],knudssøns_street).
composite_road(knut,[glomsaas,street],knut_glomsaas_street).
composite_road(knut,[glomsaas_street],knut_glomsaas_street).
composite_road(knut,[hamsuns,street],knut_hamsuns_street).
composite_road(knut,[hamsuns_street],knut_hamsuns_street).
composite_road(kobbes,[street],kobbes_street).
composite_road(koefoedgeilan,[],koefoedgeilan).
composite_road(koieflata,[],koieflata).
composite_road(kolbjørn,[hejes,street],kolbjørn_hejes_street).
composite_road(kolbjørn,[hejes_street],kolbjørn_hejes_street).
composite_road(kolstadflata,[],kolstadflata).
composite_road(kolstadtunet,[],kolstadtunet).
composite_road(kolsåsen,[],kolsåsen).
composite_road(komet,[street],komet_street).
composite_road(kong,[inges,street],kong_inges_street).
composite_road(kong,[inges_street],kong_inges_street).
composite_road(kong,[øysteins,street],kong_øysteins_street).
composite_road(kong,[øysteins_street],kong_øysteins_street).
composite_road(kongens,[street],kongens_street).
composite_road(kongle,[street],kongle_street).
composite_road(kongsgårds,[street],kongsgårds_street).
composite_road(kongs,[street],kongs_street).
composite_road(konrad,[dahls,street],konrad_dahls_street).
composite_road(konrad,[dahls_street],konrad_dahls_street).
composite_road(konsul,[lorcks,street],konsul_lorcks_street).
composite_road(konsul,[lorcks_street],konsul_lorcks_street).
composite_road(konvall,[street],konvall_street).
composite_road(kornblomst,[street],kornblomst_street).
composite_road(kors,[street],kors_street).
composite_road(korsnebb,[street],korsnebb_street).
composite_road(korsvik,[alle],korsvik_alle).
composite_road(krambu,[street],krambu_street).
composite_road(kran,[street],kran_street).
composite_road(kringkastings,[street],kringkastings_street).
composite_road(kringsjå,[street],kringsjå_street).
composite_road(kristian,[larsens,street],kristian_larsens_street).
composite_road(kristian,[larsens_street],kristian_larsens_street).
composite_road(kristiansfeld,[street],kristiansfeld_street).
composite_road(kristianstensbakken,[],kristianstensbakken).
composite_road(kristoffer,[uppdals,street],kristoffer_uppdals_street).
composite_road(kristoffer,[uppdals_street],kristoffer_uppdals_street).
composite_road(krogness,[street],krogness_street).
composite_road(krokstien,[],krokstien).
composite_road(kronprins,[olavs,alle],kronprins_olavs_alle).
composite_road(kroppanmarka,[],kroppanmarka).
composite_road(kroppan,[street],kroppan_street).
composite_road(krutthusbakken,[],krutthusbakken).
composite_road(kvaalstrøa,[],kvaalstrøa).
composite_road(kvenild,[street],kvenild_street).
composite_road(kvernhusstien,[],kvernhusstien).
composite_road(kvern,[street],kvern_street).
composite_road(kvilhaug,[street],kvilhaug_street).
composite_road(kvitstein,[street],kvitstein_street).
composite_road(kystadbrinken,[],kystadbrinken).
composite_road(kystadhaugen,[],kystadhaugen).
composite_road(kystad,[alle],kystad_alle).
composite_road(kystad,[street],kystad_street).
composite_road(kystadlia,[],kystadlia).
composite_road(kyvanns,[street],kyvanns_street).
composite_road(lade,[alle],lade_alle).
composite_road(ladebekken,[],ladebekken).
composite_road(ladehammerkaia,[],ladehammerkaia).
composite_road(ladehammer,[street],ladehammer_street).
composite_road(lademoen,[kirkealle],lademoen_kirkealle).
composite_road(ladetrøa,[],ladetrøa).
composite_road(lade,[street],lade_street).
composite_road(lagmann,[dreyers,street],lagmann_dreyers_street).
composite_road(lagmann,[dreyers_street],lagmann_dreyers_street).
composite_road(lagmann,[lindboes,street],lagmann_lindboes_street).
composite_road(lagmann,[lindboes_street],lagmann_lindboes_street).
composite_road(landbruks,[street],landbruks_street).
composite_road(landstads,[street],landstads_street).
composite_road(langberga,[],langberga).
composite_road(langhaugen,[],langhaugen).
composite_road(langørgen,[],langørgen).
composite_road(langåsmyra,[],langåsmyra).
composite_road(lars,[onsagers,street],lars_onsagers_street).
composite_road(lars,[onsagers_street],lars_onsagers_street).
composite_road(lauritz,[jenssens,street],lauritz_jenssens_street).
composite_road(lauritz,[jenssens_street],lauritz_jenssens_street).
composite_road(laura,[hangerås,street],laura_hangerås_street).
composite_road(laura,[hangerås_street],laura_hangerås_street).
composite_road(lauvsanger,[street],lauvsanger_street).
composite_road(leangen,[alle],leangen_alle).
composite_road(leangen,[street],leangen_street).
composite_road(leif,[tronstads,street],leif_tronstads_street).
composite_road(leif,[tronstads_street],leif_tronstads_street).
composite_road(leikås,[street],leikås_street).
composite_road(leinvollen,[],leinvollen).
composite_road(leirbru,[street],leirbru_street).
composite_road(leirfoss,[street],leirfoss_street).
composite_road(leistadgrenda,[],leistadgrenda).
composite_road(leistad,[street],leistad_street).
composite_road(leiv,[erikssons,street],leiv_erikssons_street).
composite_road(leiv,[erikssons_street],leiv_erikssons_street).
composite_road(leksvik,[street],leksvik_street).
composite_road(lerkendal,[gård],lerkendal_gård).
composite_road(lerkendals,[street],lerkendals_street).
composite_road(lerke,[street],lerke_street).
composite_road(lianhaugen,[],lianhaugen).
composite_road(lian,[street],lian_street).
composite_road(lidarende,[],lidarende).
composite_road(lille,[lade],lille_lade).
composite_road(lilleberg,[street],lilleberg_street).
composite_road(lillegårdsbakken,[],lillegårdsbakken).
composite_road(lilleplassveita,[],lilleplassveita).
composite_road(lillerydningen,[],lillerydningen).
composite_road(lindemans,[street],lindemans_street).
composite_road(lide,[street],lide_street).
composite_road(linerle,[street],linerle_street).
composite_road(lita,[street],lita_street).
composite_road(loholt,[alle],loholt_alle).
composite_road(loholtbakken,[],loholtbakken).
composite_road(lokes,[street],lokes_street).
composite_road(los,[street],los_street).
composite_road(losje,[street],losje_street).
composite_road(lossius,[street],lossius_street).
composite_road(louis,[kvalstads,street],louis_kvalstads_street).
composite_road(louis,[kvalstads_street],louis_kvalstads_street).
composite_road(ludvig,[daaes,street],ludvig_daaes_street).
composite_road(ludvig,[daaes_street],ludvig_daaes_street).
composite_road(ludvig,[musts,street],ludvig_musts_street).
composite_road(ludvig,[musts_street],ludvig_musts_street).
composite_road(luna,[street],luna_street).
composite_road(lundemobakken,[],lundemobakken).
composite_road(lunderhaugen,[],lunderhaugen).
composite_road(lundhøgda,[],lundhøgda).
composite_road(lund,[street],lund_street).
composite_road(lundåsen,[],lundåsen).
composite_road(lykkestien,[],lykkestien).
composite_road(lykkmarka,[],lykkmarka).
composite_road(lyng,[street],lyng_street).
composite_road(løkke,[street],løkke_street).
composite_road(lønn,[street],lønn_street).
composite_road(løvaas,[street],løvaas_street).
composite_road(løvetann,[street],løvetann_street).
composite_road(løytnants,[street],løytnants_street).
composite_road(magasin,[street],magasin_street).
composite_road(magnus,[berrføtts,street],magnus_berrføtts_street).
composite_road(magnus,[berrføtts_street],magnus_berrføtts_street).
composite_road(magnus,[blindes,street],magnus_blindes_street).
composite_road(magnus,[blindes_street],magnus_blindes_street).
composite_road(magnus,[den,godes,street],magnus_den_godes_street).
composite_road(magnus,[den,godes_street],magnus_den_godes_street).
composite_road(magnus,[halvorsens,street],magnus_halvorsens_street).
composite_road(magnus,[halvorsens_street],magnus_halvorsens_street).
composite_road(magnus,[lagabøters,street],magnus_lagabøters_street).
composite_road(magnus,[lagabøters_street],magnus_lagabøters_street).
composite_road(marcus,[thranes,street],marcus_thranes_street).
composite_road(marcus,[thranes_street],marcus_thranes_street).
composite_road(margretes,[street],margretes_street).
composite_road(marie,[michelets,street],marie_michelets_street).
composite_road(marie,[michelets_street],marie_michelets_street).
composite_road(marie,[sørdals,street],marie_sørdals_street).
composite_road(marie,[sørdals_street],marie_sørdals_street).
composite_road(marie,[wexelsens,street],marie_wexelsens_street).
composite_road(marie,[wexelsens_street],marie_wexelsens_street).
composite_road(marienberg,[street],marienberg_street).
composite_road(marienlyst,[street],marienlyst_street).
composite_road(maristu,[street],maristu_street).
composite_road(marit,[fladaas,street],marit_fladaas_street).
composite_road(marit,[fladaas_street],marit_fladaas_street).
composite_road(markaplassen,[],markaplassen).
composite_road(mark,[street],mark_street).
composite_road(mars,[street],mars_street).
composite_road(martin,[barstads,street],martin_barstads_street).
composite_road(martin,[barstads_street],martin_barstads_street).
composite_road(martin,[haugens,street],martin_haugens_street).
composite_road(martin,[haugens_street],martin_haugens_street).
composite_road(martin,[linges,street],martin_linges_street).
composite_road(martin,[linges_street],martin_linges_street).
composite_road(martin,[kregnes,street],martin_kregnes_street).
composite_road(martin,[kregnes_street],martin_kregnes_street).
composite_road(martin,[stokkens,street],martin_stokkens_street).
composite_road(martin,[stokkens_street],martin_stokkens_street).
composite_road(martin,[sæterhaugs,street],martin_sæterhaugs_street).
composite_road(martin,[sæterhaugs_street],martin_sæterhaugs_street).
composite_road(maskinist,[street],maskinist_street).
composite_road(mauritz,[hansens,street],mauritz_hansens_street).
composite_road(mauritz,[hansens_street],mauritz_hansens_street).
composite_road(meise,[street],meise_street).
composite_road(meisterlins,[street],meisterlins_street).
composite_road(mellomfoss,[street],mellomfoss_street).
composite_road(mellomila,[],mellomila).
composite_road(mellom,[street],mellom_street).
composite_road(mentz,[skjetnes,street],mentz_skjetnes_street).
composite_road(mentz,[skjetnes_street],mentz_skjetnes_street).
composite_road(merkur,[street],merkur_street).
composite_road(meteor,[street],meteor_street).
composite_road(micael,[smiths,street],micael_smiths_street).
composite_road(micael,[smiths_street],micael_smiths_street).
composite_road(michel,[grendahls,street],michel_grendahls_street).
composite_road(michel,[grendahls_street],michel_grendahls_street).
composite_road(midelfarts,[street],midelfarts_street).
composite_road(midteggen,[],midteggen).
composite_road(midtre,[tunhøgda],midtre_tunhøgda).
composite_road(mikkel,[mærks,street],mikkel_mærks_street).
composite_road(mikkel,[mærks_street],mikkel_mærks_street).
composite_road(mikkel,[street],mikkel_street).
composite_road(mjølner,[street],mjølner_street).
composite_road(mogstads,[street],mogstads_street).
composite_road(moholt,[alle],moholt_alle).
composite_road(moholtlia,[],moholtlia).
composite_road(moholtsvingen,[],moholtsvingen).
composite_road(moltmyra,[],moltmyra).
composite_road(moslings,[street],moslings_street).
composite_road(motzfeldts,[street],motzfeldts_street).
composite_road(mulberga,[],mulberga).
composite_road(munins,[street],munins_street).
composite_road(munke,[street],munke_street).
composite_road(munkhaugveita,[],munkhaugveita).
composite_road(munkvollstien,[],munkvollstien).
composite_road(munkvoll,[street],munkvoll_street).
composite_road(museumsplass,[],museumsplass).
composite_road(myrmanns,[street],myrmanns_street).
composite_road(myrsnipe,[street],myrsnipe_street).
composite_road(myrstad,[street],myrstad_street).
composite_road(myrsund,[street],myrsund_street).
composite_road(myrtunet,[],myrtunet).
composite_road(myrvangsvingen,[],myrvangsvingen).
composite_road(møllebakken,[],møllebakken).
composite_road(møllehaugen,[],møllehaugen).
composite_road(mørlenda,[],mørlenda).
composite_road(mår,[street],mår_street).
composite_road(nardobakken,[],nardobakken).
composite_road(nardoskrenten,[],nardoskrenten).
composite_road(nardo,[street],nardo_street).
composite_road(nedre,[alle],nedre_alle).
composite_road(nedre,[bakklandet],nedre_bakklandet).
composite_road(nedre,[bergsvingen],nedre_bergsvingen).
composite_road(nedre,[enkeltskillingsveita],nedre_enkeltskillingsveita).
composite_road(nedre,[ferstad,street],nedre_ferstad_street).
composite_road(nedre,[ferstad_street],nedre_ferstad_street).
composite_road(nedre,[flatås,street],nedre_flatås_street).
composite_road(nedre,[flatås_street],nedre_flatås_street).
composite_road(nedre,[grilstadkleiva],nedre_grilstadkleiva).
composite_road(nedre,[ila],nedre_ila).
composite_road(nedre,[kristianstens,street],nedre_kristianstens_street).
composite_road(nedre,[kristianstens_street],nedre_kristianstens_street).
composite_road(nedre,[møllenberg,street],nedre_møllenberg_street).
composite_road(nedre,[møllenberg_street],nedre_møllenberg_street).
composite_road(nedre,[sjetnhaugan],nedre_sjetnhaugan).
composite_road(neptun,[street],neptun_street).
composite_road(nergeilan,[],nergeilan).
composite_road(nermarka,[],nermarka).
composite_road(nertrøa,[],nertrøa).
composite_road(nerviks,[street],nerviks_street).
composite_road(neufeldts,[street],neufeldts_street).
composite_road(nidareid,[],nidareid).
composite_road(nidarholms,[street],nidarholms_street).
composite_road(nidarøy,[street],nidarøy_street).
composite_road(nils,[ryjords,street],nils_ryjords_street).
composite_road(nils,[ryjords_street],nils_ryjords_street).
composite_road(nils,[stavnes,street],nils_stavnes_street).
composite_road(nils,[stavnes_street],nils_stavnes_street).
composite_road(nils,[uhlin,hansens,street],nils_uhlin_hansens_street).
composite_road(nils,[uhlin,hansens_street],nils_uhlin_hansens_street).
composite_road(nina,[griegs,street],nina_griegs_street).
composite_road(nina,[griegs_street],nina_griegs_street).
composite_road(njardarvollen,[],njardarvollen).
composite_road(njords,[street],njords_street).
composite_road(nonne,[street],nonne_street).
composite_road(nordahl,[bruns,street],nordahl_bruns_street).
composite_road(nordahl,[bruns_street],nordahl_bruns_street).
composite_road(nordahl,[griegs,street],nordahl_griegs_street).
composite_road(nordahl,[griegs_street],nordahl_griegs_street).
composite_road(nordbakken,[],nordbakken).
composite_road(nordhaugs,[street],nordhaugs_street).
composite_road(nordli,[street],nordli_street).
composite_road(nordlund,[street],nordlund_street).
composite_road(nordmyr,[street],nordmyr_street).
composite_road(nordre,[berg,street],nordre_berg_street).
composite_road(nordre,[berg_street],nordre_berg_street).
composite_road(nordre,[eberg,street],nordre_eberg_street).
composite_road(nordre,[eberg_street],nordre_eberg_street).
composite_road(nordre,[hallset,street],nordre_hallset_street).
composite_road(nordre,[hallset_street],nordre_hallset_street).
composite_road(nordre,[husebytun],nordre_husebytun).
composite_road(nordre,[jons,street],nordre_jons_street).
composite_road(nordre,[jons_street],nordre_jons_street).
composite_road(nordre,[risvolltun],nordre_risvolltun).
composite_road(nordre,[street],nordre_street).
composite_road(nordslett,[street],nordslett_street).
composite_road(nordtvedts,[street],nordtvedts_street).
composite_road(norne,[street],norne_street).
composite_road(norrkøping,[street],norrkøping_street).
composite_road(ny,[steinsbakken],ny_steinsbakken).
composite_road(ny,[street],ny_street).
composite_road(nygård,[street],nygård_street).
composite_road(nyheims,[street],nyheims_street).
composite_road(nyplia,[],nyplia).
composite_road(nypan,[],nypan).
composite_road(nyveibakken,[],nyveibakken).
composite_road(nyveilia,[],nyveilia).
composite_road(o,[j,aalmos,street],o_j_aalmos_street).
composite_road(o,[j,aalmos_street],o_j_aalmos_street).
composite_road(odd,[husbys,street],odd_husbys_street).
composite_road(odd,[husbys_street],odd_husbys_street).
composite_road(odd,[sørlis,street],odd_sørlis_street).
composite_road(odd,[sørlis_street],odd_sørlis_street).
composite_road(odense,[street],odense_street).
composite_road(odins,[street],odins_street).
composite_road(okstad,[street],okstad_street).
composite_road(okstad,[ø],okstad_ø).
composite_road(okstadbrinken,[],okstadbrinken).
composite_road(okstadplassen,[],okstadplassen).
composite_road(okstadøy,[],okstadøy).
composite_road(ola,[frosts,street],ola_frosts_street). %% TA-110518
composite_road(ola,[setroms,street],ola_setroms_street).
composite_road(ola,[setroms_street],ola_setroms_street).
composite_road(olaf,[bulls,street],olaf_bulls_street).
composite_road(olaf,[bulls_street],olaf_bulls_street).
composite_road(olaf,[grilstads,street],olaf_grilstads_street).
composite_road(olaf,[grilstads_street],olaf_grilstads_street).
composite_road(olaf,[nordhagens,street],olaf_nordhagens_street).
composite_road(olaf,[nordhagens_street],olaf_nordhagens_street).
composite_road(olav,[aukrusts,street],olav_aukrusts_street).
composite_road(olav,[aukrusts_street],olav_aukrusts_street).
composite_road(olav,[duuns,street],olav_duuns_street).
composite_road(olav,[duuns_street],olav_duuns_street).
composite_road(olav,[engelbrektssons,alle],olav_engelbrektssons_alle).
composite_road(olav,[gullvågs,street],olav_gullvågs_street).
composite_road(olav,[gullvågs_street],olav_gullvågs_street).
composite_road(olav,[kyrres,street],olav_kyrres_street).
composite_road(olav,[kyrres_street],olav_kyrres_street).
composite_road(olav,[magnussons,street],olav_magnussons_street).
composite_road(olav,[magnussons_street],olav_magnussons_street).
composite_road(olav,[nygards,street],olav_nygards_street).
composite_road(olav,[nygards_street],olav_nygards_street).
composite_road(olav,[trondsons,street],olav_trondsons_street).
composite_road(olav,[trondsons_street],olav_trondsons_street).
composite_road(olav,[tryggvasons,street],olav_tryggvasons_street).
composite_road(olav,[tryggvasons_street],olav_tryggvasons_street).
composite_road(olav,[vasseljens,street],olav_vasseljens_street).
composite_road(olav,[vasseljens_street],olav_vasseljens_street).
composite_road(older,[street],older_street).
composite_road(ole,[a,wolds,street],ole_a_wolds_street).
composite_road(ole,[a,wolds_street],ole_a_wolds_street).



composite_road(ole,[hogstads,street],ole_hogstads_street).
composite_road(ole,[hogstads_street],ole_hogstads_street).
composite_road(ole,[jørgensens,street],ole_jørgensens_street).
composite_road(ole,[jørgensens_street],ole_jørgensens_street).
composite_road(ole,[l,kolstads,street],ole_l_kolstads_street).
composite_road(ole,[l,kolstads_street],ole_l_kolstads_street).
composite_road(ole,[laulos,street],ole_laulos_street).
composite_road(ole,[laulos_street],ole_laulos_street).
composite_road(ole,[nordgaards,street],ole_nordgaards_street).
composite_road(ole,[nordgaards_street],ole_nordgaards_street).
composite_road(ole,[ross,street],ole_ross_street).
composite_road(ole,[ross_street],ole_ross_street).
composite_road(ole,[rølvaags,street],ole_rølvaags_street).
composite_road(ole,[rølvaags_street],ole_rølvaags_street).
composite_road(ole,[skolemesters,street],ole_skolemesters_street).
composite_road(ole,[skolemesters_street],ole_skolemesters_street).
composite_road(ole,[soelbergs,street],ole_soelbergs_street).
composite_road(ole,[soelbergs_street],ole_soelbergs_street).
composite_road(ole,[tesliens,street],ole_tesliens_street).
composite_road(ole,[tesliens_street],ole_tesliens_street).
composite_road(ole,[tilseths,street],ole_tilseths_street).
composite_road(ole,[tilseths_street],ole_tilseths_street).
composite_road(ole,[vigs,street],ole_vigs_street).
composite_road(ole,[vigs_street],ole_vigs_street).
composite_road(ole,[øisangs,street],ole_øisangs_street).
composite_road(ole,[øisangs_street],ole_øisangs_street).
composite_road(oline,[hårstads,street],oline_hårstads_street).
composite_road(oline,[hårstads_street],oline_hårstads_street).
composite_road(oppsynsmann,[eggens,street],oppsynsmann_eggens_street).
composite_road(oppsynsmann,[eggens_street],oppsynsmann_eggens_street).
composite_road(orion,[street],orion_street).
composite_road(ormen,[langes,street],ormen_langes_street).
composite_road(ormen,[langes_street],ormen_langes_street).
composite_road(orre,[street],orre_street).
composite_road(o,[s,bragstads,plass],o_s_bragstads_plass).
composite_road(oscar,[wistings,street],oscar_wistings_street).
composite_road(oscar,[wistings_street],oscar_wistings_street).
composite_road(oskar,[braatens,street],oskar_braatens_street).
composite_road(oskar,[braatens_street],oskar_braatens_street).
composite_road(oskar,[skaugs,street],oskar_skaugs_street).
composite_road(oskar,[skaugs_street],oskar_skaugs_street).
composite_road(oslo,[street],oslo_street).
composite_road(os,[street],os_street).
composite_road(othilienborgtunet,[],othilienborgtunet).
composite_road(othilienborg,[street],othilienborg_street).
composite_road(ottars,[street],ottars_street).
composite_road(otto,[nielsens,street],otto_nielsens_street).
composite_road(otto,[nielsens_street],otto_nielsens_street).
composite_road(otto,[skirstads,street],otto_skirstads_street).
composite_road(otto,[skirstads_street],otto_skirstads_street).
composite_road(ottobyen,[],ottobyen).
composite_road(oustmyr,[street],oustmyr_street).
composite_road(overlege,[bratts,street],overlege_bratts_street).
composite_road(overlege,[bratts_street],overlege_bratts_street).
composite_road(overlege,[kindts,street],overlege_kindts_street).
composite_road(overlege,[kindts_street],overlege_kindts_street).
composite_road(overviks,[street],overviks_street).
composite_road(p,[a,munchs,street],p_a_munchs_street).
composite_road(p,[a,munchs_street],p_a_munchs_street).
composite_road(parallellen,[],parallellen).
composite_road(park,[street],park_street).
composite_road(paul,[fjermstads,street],paul_fjermstads_street).
composite_road(paul,[fjermstads_street],paul_fjermstads_street).
composite_road(paul,[skolemesters,street],paul_skolemesters_street).
composite_road(paul,[skolemesters_street],paul_skolemesters_street).
composite_road(peder,[kroghs,street],peder_kroghs_street).
composite_road(peder,[kroghs_street],peder_kroghs_street).
composite_road(peder,[morsets,street],peder_morsets_street).
composite_road(peder,[morsets_street],peder_morsets_street).
composite_road(peder,[myhres,street],peder_myhres_street).
composite_road(peder,[myhres_street],peder_myhres_street).
composite_road(peder,[østlunds,street],peder_østlunds_street).
composite_road(peder,[østlunds_street],peder_østlunds_street).
composite_road(per,[halvorsens,street],per_halvorsens_street).
composite_road(per,[halvorsens_street],per_halvorsens_street).
composite_road(per,[kvists,street],per_kvists_street).
composite_road(per,[kvists_street],per_kvists_street).
composite_road(per,[lykkes,street],per_lykkes_street).
composite_road(per,[lykkes_street],per_lykkes_street).
composite_road(per,[sivles,street],per_sivles_street).
composite_road(per,[sivles_street],per_sivles_street).
composite_road(persaun,[street],persaun_street).
composite_road(persberg,[street],persberg_street).
composite_road(perslia,[],perslia).
composite_road(persløkk,[street],persløkk_street).
composite_road(peter,[egges,plass],peter_egges_plass).
composite_road(peter,[egges,street],peter_egges_street).
composite_road(peter,[egges_street],peter_egges_street).
composite_road(peter,[wanviks,street],peter_wanviks_street).
composite_road(peter,[wanviks_street],peter_wanviks_street).
composite_road(petersborg,[],petersborg).
composite_road(petersborg,[street],petersborg_street).
composite_road(petter,[lies,street],petter_lies_street).
composite_road(petter,[lies_street],petter_lies_street).
composite_road(pianist,[sandbergs,street],pianist_sandbergs_street).
composite_road(pianist,[sandbergs_street],pianist_sandbergs_street).
composite_road(pilegrimsstien,[],pilegrimsstien).
composite_road(pinebergsvingen,[],pinebergsvingen).
composite_road(pineberg,[street],pineberg_street).
composite_road(pir,[i],pir_i).
composite_road(pir,[ii],pir_ii).
composite_road(planet,[street],planet_street).
composite_road(pluto,[street],pluto_street).
composite_road(port,[arthur],port_arthur).
composite_road(poppel,[street],poppel_street).
composite_road(porsmyra,[],porsmyra).
composite_road(pottemaker,[street],pottemaker_street).
composite_road(prestegårds,[street],prestegårds_street).
composite_road(prestekrage,[street],prestekrage_street).
composite_road(presthus,[street],presthus_street).
composite_road(prestmo,[street],prestmo_street).
composite_road(prinsens,[street],prinsens_street).
composite_road(prinsesse,[street],prinsesse_street).
composite_road(professor,[brochs,street],professor_brochs_street).
composite_road(professor,[brochs_street],professor_brochs_street).
composite_road(professor,[j,h,l,vogts,street],professor_j_h_l_vogts_street).
composite_road(professor,[mørchs,street],professor_mørchs_street).
composite_road(professor,[mørchs_street],professor_mørchs_street).
composite_road(professor,[street],professor_street).
composite_road(prost,[castbergs,street],prost_castbergs_street).
composite_road(prost,[castbergs_street],prost_castbergs_street).
composite_road(ragnhilds,[street],ragnhilds_street).
composite_road(ramsharts,[street],ramsharts_street).
composite_road(randi,[kjærems,street],randi_kjærems_street).
composite_road(randi,[kjærems_street],randi_kjærems_street).
composite_road(ranheim,[lille],ranheim_lille).
composite_road(ranheimshøgda,[],ranheimshøgda).
composite_road(ranheimsli,[street],ranheimsli_street).
composite_road(ranheimsmoen,[],ranheimsmoen).
composite_road(ranheims,[street],ranheims_street).
composite_road(ratesvingen,[],ratesvingen).
composite_road(ravelsveita,[],ravelsveita).
composite_road(reidar,[lyseths,street],reidar_lyseths_street).
composite_road(reidar,[lyseths_street],reidar_lyseths_street).
composite_road(reidar,[raaens,street],reidar_raaens_street).
composite_road(reidar,[raaens_street],reidar_raaens_street).
composite_road(reidulvs,[street],reidulvs_street).
composite_road(reina,[],reina).
composite_road(reitanstien,[],reitanstien).
composite_road(reppe,[street],reppe_street).
composite_road(repslagerveita,[],repslagerveita).
composite_road(richard,[birkelands,street],richard_birkelands_street).
composite_road(richard,[birkelands_street],richard_birkelands_street).
composite_road(richard,[withs,street],richard_withs_street).
composite_road(richard,[withs_street],richard_withs_street).
composite_road(riddervolds,[street],riddervolds_street).
composite_road(riiser,[larsens,street],riiser_larsens_street).
composite_road(riiser,[larsens_street],riiser_larsens_street).
composite_road(rimfakse,[street],rimfakse_street).
composite_road(ringdue,[street],ringdue_street).
composite_road(ring,[street],ring_street).
composite_road(ringvålhaugen,[],ringvålhaugen).
composite_road(ringvål,[street],ringvål_street).
composite_road(rismo,[street],rismo_street).
composite_road(risvoll,[street],risvoll_street).
composite_road(rittmester,[street],rittmester_street).
composite_road(roald,[amundsens,street],roald_amundsens_street).
composite_road(roald,[amundsens_street],roald_amundsens_street).
composite_road(rogerts,[street],rogerts_street).
composite_road(rognbudalen,[],rognbudalen).
composite_road(rognersvingen,[],rognersvingen).
composite_road(rogner,[street],rogner_street).
composite_road(romemyra,[],romemyra).
composite_road(romulslia,[],romulslia).
composite_road(roosevelts,[street],roosevelts_street).
composite_road(rosenborg,[street],rosenborg_street).
composite_road(rostengrenda,[],rostengrenda).
composite_road(rotvoll,[alle],rotvoll_alle).
composite_road(rudolf,[nilsens,street],rudolf_nilsens_street).
composite_road(rudolf,[nilsens_street],rudolf_nilsens_street).
composite_road(rudolf,[ræders,street],rudolf_ræders_street).
composite_road(rudolf,[ræders_street],rudolf_ræders_street).
composite_road(rugde,[street],rugde_street).
composite_road(rydningen,[],rydningen).
composite_road(rype,[street],rype_street).
composite_road(rødrev,[street],rødrev_street).
composite_road(rødstilk,[street],rødstilk_street).
composite_road(røllik,[street],røllik_street).
composite_road(rønningsbakken,[],rønningsbakken).
composite_road(rønnings,[street],rønnings_street).
composite_road(rørosstien,[],rørosstien).
composite_road(røsslyng,[street],røsslyng_street).
composite_road(røyskatt,[street],røyskatt_street).
composite_road(rådmann,[hammers,street],rådmann_hammers_street).
composite_road(rådmann,[hammers_street],rådmann_hammers_street).
composite_road(rådmanns,[street],rådmanns_street).
composite_road(rådyr,[street],rådyr_street).
composite_road(s,[p,andersens,street],s_p_andersens_street).
composite_road(s,[p,andersens_street],s_p_andersens_street).
composite_road(sandbakk,[street],sandbakk_street).
composite_road(sagberget,[],sagberget).
composite_road(sagplass,[street],sagplass_street).
composite_road(sag,[street],sag_street).
composite_road(sandborgs,[street],sandborgs_street).
composite_road(sand,[street],sand_street).
composite_road(sandmo,[street],sandmo_street).
composite_road(saturn,[street],saturn_street).
composite_road(saupstadbrinken,[],saupstadbrinken).
composite_road(saupstadringen,[],saupstadringen).
composite_road(saxenborg,[alle],saxenborg_alle).
composite_road(schirmers,[street],schirmers_street).
composite_road(schives,[street],schives_street).
composite_road(schiøtz,[street],schiøtz_street).
composite_road(schjoldagerveita,[],schjoldagerveita).
composite_road(schmidts,[street],schmidts_street).
composite_road(schnitlers,[street],schnitlers_street).
composite_road(schultz,[street],schultz_street).
composite_road(schwachs,[street],schwachs_street).
composite_road(schøllers,[street],schøllers_street).
composite_road(schøningsdal,[],schøningsdal).
composite_road(schøyens,[street],schøyens_street).
composite_road(selje,[street],selje_street).
composite_road(selsbakk,[øvre],selsbakk_øvre).
composite_road(selsbakkflata,[],selsbakkflata).
composite_road(selsbakk,[street],selsbakk_street).
composite_road(sem,[sælands,street],sem_sælands_street).
composite_road(sem,[sælands_street],sem_sælands_street).
composite_road(serinelyst,[street],serinelyst_street).
composite_road(severin,[saksviks,street],severin_saksviks_street).
composite_road(severin,[saksviks_street],severin_saksviks_street).
composite_road(sigmunds,[street],sigmunds_street).
composite_road(sigmunn,[jakobsens,street],sigmunn_jakobsens_street).
composite_road(sigmunn,[jakobsens_street],sigmunn_jakobsens_street).
composite_road(sigrid,[johansens,street],sigrid_johansens_street).
composite_road(sigrid,[johansens_street],sigrid_johansens_street).
composite_road(sigrid,[undsets,street],sigrid_undsets_street).
composite_road(sigrid,[undsets_street],sigrid_undsets_street).
composite_road(sigurd,[bergs,alle],sigurd_bergs_alle).
composite_road(sigurd,[einbus,street],sigurd_einbus_street).
composite_road(sigurd,[einbus_street],sigurd_einbus_street).
composite_road(sigurd,[hoels,street],sigurd_hoels_street).
composite_road(sigurd,[hoels_street],sigurd_hoels_street).
composite_road(sigurd,[høidals,street],sigurd_høidals_street).
composite_road(sigurd,[høidals_street],sigurd_høidals_street).
composite_road(sigurd,[jorsalfars,street],sigurd_jorsalfars_street).
composite_road(sigurd,[jorsalfars_street],sigurd_jorsalfars_street).
composite_road(sigurd,[munns,street],sigurd_munns_street).
composite_road(sigurd,[munns_street],sigurd_munns_street).
composite_road(sigurd,[slembes,street],sigurd_slembes_street).
composite_road(sigurd,[slembes_street],sigurd_slembes_street).
composite_road(sildråpe,[street],sildråpe_street).
composite_road(simon,[leinums,street],simon_leinums_street).
composite_road(simon,[leinums_street],simon_leinums_street).
composite_road(simonsens,[street],simonsens_street).
composite_road(singsakerbakken,[],singsakerbakken).
composite_road(sirius,[street],sirius_street).
composite_road(sisik,[street],sisik_street).
composite_road(sivert,[dalens,street],sivert_dalens_street).
composite_road(sivert,[dalens_street],sivert_dalens_street).
composite_road(sivert,[gjørtlers,street],sivert_gjørtlers_street).
composite_road(sivert,[gjørtlers_street],sivert_gjørtlers_street).
composite_road(sivert,[thonstads,street],sivert_thonstads_street).
composite_road(sivert,[thonstads_street],sivert_thonstads_street).
composite_road(sjømanns,[street],sjømanns_street).
composite_road(sjø,[street],sjø_street).
composite_road(skans,[street],skans_street).
composite_road(skarsleite,[],skarsleite).
composite_road(skavlans,[street],skavlans_street).
composite_road(skipper,[street],skipper_street).
composite_road(skjerm,[street],skjerm_street).
composite_road(skjetnemark,[street],skjetnemark_street).
composite_road(skjæringen,[],skjæringen).
composite_road(skogmus,[street],skogmus_street).
composite_road(skog,[street],skog_street).
composite_road(skogvokter,[street],skogvokter_street).
composite_road(skole,[street],skole_street).
composite_road(skrenten,[],skrenten).
composite_road(skråstien,[],skråstien).
composite_road(skule,[bårdsøns,street],skule_bårdsøns_street).
composite_road(skule,[bårdsøns_street],skule_bårdsøns_street).
composite_road(skytter,[street],skytter_street).
composite_road(skyås,[street],skyås_street).
composite_road(skårgangen,[],skårgangen).
composite_road(sleipnes,[street],sleipnes_street).
composite_road(sluppen,[street],sluppen_street).
composite_road(smed,[johns,street],smed_johns_street).
composite_road(smed,[johns_street],smed_johns_street).
composite_road(smedbakken,[],smedbakken).
composite_road(smedstu,[street],smedstu_street).
composite_road(smørblomst,[street],smørblomst_street).
composite_road(snorres,[street],snorres_street).
composite_road(sodemanns,[street],sodemanns_street).
composite_road(solbakkestien,[],solbakkestien).
composite_road(solborg,[street],solborg_street).
composite_road(solems,[street],solems_street).
composite_road(solhøgd,[street],solhøgd_street).
composite_road(solvangen,[],solvangen).
composite_road(solvoll,[street],solvoll_street).
composite_road(sommerfjøs,[street],sommerfjøs_street).
composite_road(sommerlyst,[street],sommerlyst_street).
composite_road(sommerveita,[],sommerveita).
composite_road(sorgenfri,[street],sorgenfri_street).
composite_road(spove,[street],spove_street).
composite_road(st,[jørgensveita],st_jørgensveita).
composite_road(st,[olavs,street],st_olavs_street).
composite_road(st,[olavs_street],st_olavs_street).
composite_road(stabells,[street],stabells_street).
composite_road(stadsing,[dahls,street],stadsing_dahls_street).
composite_road(stadsing,[dahls_street],stadsing_dahls_street).
composite_road(stallmester,[street],stallmester_street).
composite_road(stampestien,[],stampestien).
composite_road(stampeverks,[street],stampeverks_street).
composite_road(stare,[street],stare_street).
composite_road(starrmyra,[],starrmyra).
composite_road(statsråd,[kroghs,street],statsråd_kroghs_street).
composite_road(statsråd,[kroghs_street],statsråd_kroghs_street).
composite_road(stavnemo,[street],stavnemo_street).
composite_road(stavsetsvingen,[],stavsetsvingen).
composite_road(stavset,[street],stavset_street).
composite_road(stavs,[street],stavs_street).
composite_road(steinan,[street],steinan_street).
composite_road(steinberget,[],steinberget).
composite_road(steindals,[street],steindals_street).
composite_road(steinhaugen,[],steinhaugen).
composite_road(steinrabben,[],steinrabben).
composite_road(steintrø,[street],steintrø_street).
composite_road(steinåsen,[],steinåsen).
composite_road(stiklestad,[street],stiklestad_street).
composite_road(stjørdals,[street],stjørdals_street).
composite_road(stokkanhaugen,[],stokkanhaugen).
composite_road(stokkbekken,[],stokkbekken).
composite_road(stolpstu,[street],stolpstu_street).
composite_road(storflata,[],storflata).
composite_road(storhaugstien,[],storhaugstien).
composite_road(strand,[street],strand_street).
composite_road(strindheim,[street],strindheim_street).
composite_road(strind,[street],strind_street).
composite_road(stubban,[street],stubban_street).
composite_road(stubbsvingen,[],stubbsvingen).
composite_road(stubb,[street],stubb_street).
composite_road(stutt,[street],stutt_street).
composite_road(styrmanns,[street],styrmanns_street).
composite_road(sundlandskrenten,[],sundlandskrenten).
composite_road(sundlands,[street],sundlands_street).
composite_road(svale,[street],svale_street).
composite_road(svalsbergstien,[],svalsbergstien).
composite_road(svartholtet,[],svartholtet).
composite_road(sveiser,[street],sveiser_street).
composite_road(sverdrups,[street],sverdrups_street).
composite_road(sverre,[støstads,street],sverre_støstads_street).
composite_road(sverre,[støstads_street],sverre_støstads_street).
composite_road(sverre,[svendsens,street],sverre_svendsens_street).
composite_road(sverre,[svendsens_street],sverre_svendsens_street).
composite_road(sverres,[street],sverres_street).
composite_road(sverresborg,[alle],sverresborg_alle).
composite_road(sverresdals,[street],sverresdals_street).
composite_road(svolder,[street],svolder_street).
composite_road(sylvester,[sivertsons,street],sylvester_sivertsons_street).
composite_road(sylvester,[sivertsons_street],sylvester_sivertsons_street).
composite_road(symre,[street],symre_street).
composite_road(syrin,[street],syrin_street).
composite_road(sæterbakken,[],sæterbakken).
composite_road(søbstad,[street],søbstad_street).
composite_road(søndre,[eberg,street],søndre_eberg_street).
composite_road(søndre,[eberg_street],søndre_eberg_street).
composite_road(søndre,[husebytun],søndre_husebytun).
composite_road(søndre,[jons,street],søndre_jons_street).
composite_road(søndre,[jons_street],søndre_jons_street).
composite_road(søndre,[risvolltun],søndre_risvolltun).
composite_road(søndre,[street],søndre_street).
composite_road(søra,[street],søra_street).
composite_road(sørbru,[street],sørbru_street).
composite_road(sørenga,[],sørenga).
composite_road(tamburhaugen,[],tamburhaugen).
composite_road(tambs,[lyches,street],tambs_lyches_street).
composite_road(tambs,[lyches_street],tambs_lyches_street).
composite_road(tampere,[street],tampere_street).
composite_road(tank,[street],tank_street).
composite_road(taraldsgårdsveita,[],taraldsgårdsveita).
composite_road(teglbrenner,[street],teglbrenner_street).
composite_road(teglverket,[],teglverket).
composite_road(teglverkstunet,[],teglverkstunet).
composite_road(tellefsens,[street],tellefsens_street).
composite_road(tempe,[street],tempe_street).
composite_road(terminalen,[],terminalen).
composite_road(tesli,[],tesli).
composite_road(tessems,[street],tessems_street).
composite_road(thaulowbakken,[],thaulowbakken).
composite_road(theodor,[petersens,street],theodor_petersens_street).
composite_road(theodor,[petersens_street],theodor_petersens_street).
composite_road(thomas,[angells,street],thomas_angells_street).
composite_road(thomas,[angells_street],thomas_angells_street).
composite_road(thomas,[hirschs,street],thomas_hirschs_street).
composite_road(thomas,[hirschs_street],thomas_hirschs_street).
composite_road(thomas,[von,westens,street],thomas_von_westens_street).
composite_road(thomas,[von,westens_street],thomas_von_westens_street).
composite_road(thonning,[owesens,street],thonning_owesens_street).
composite_road(thonning,[owesens_street],thonning_owesens_street).
composite_road(thora,[storms,street],thora_storms_street).
composite_road(thora,[storms_street],thora_storms_street).
composite_road(thorry,[kiærs,street],thorry_kiærs_street).
composite_road(thorry,[kiærs_street],thorry_kiærs_street).
composite_road(thorvald,[erichsens,street],thorvald_erichsens_street).
composite_road(thorvald,[erichsens_street],thorvald_erichsens_street).
composite_road(thrond,[nergaards,street],thrond_nergaards_street).
composite_road(thrond,[nergaards_street],thrond_nergaards_street).
composite_road(tidemands,[street],tidemands_street).
composite_road(tillerbru,[street],tillerbru_street).
composite_road(tiller,[ringen],tiller_ringen).
composite_road(tilleråsen,[],tilleråsen).
composite_road(tinghusplassen,[],tinghusplassen).
composite_road(ting,[street],ting_street).
composite_road(tistel,[street],tistel_street).
composite_road(tiur,[street],tiur_street).
composite_road(tone,[street],tone_street).
composite_road(tonstadbrinken,[],tonstadbrinken).
composite_road(tonstadgrenda,[],tonstadgrenda).
composite_road(torbjørn,[bratts,street],torbjørn_bratts_street).
composite_road(torbjørn,[bratts_street],torbjørn_bratts_street).
composite_road(tordenskiolds,[street],tordenskiolds_street).
composite_road(tormods,[street],tormods_street).
composite_road(torplassen,[],torplassen).
composite_road(tors,[street],tors_street).
composite_road(torshaug,[street],torshaug_street).
composite_road(torvmyra,[],torvmyra).
composite_road(torvtaket,[],torvtaket).
composite_road(trane,[street],trane_street).
composite_road(transitt,[street],transitt_street).
composite_road(travbane,[street],travbane_street).
composite_road(trofet,[street],trofet_street).
composite_road(trollahaugen,[],trollahaugen).
composite_road(trollsvingen,[],trollsvingen).
composite_road(trudevang,[street],trudevang_street).
composite_road(trygve,[thesens,street],trygve_thesens_street).
composite_road(trygve,[thesens_street],trygve_thesens_street).
composite_road(tryms,[street],tryms_street).
composite_road(trøa,[street],trøa_street).
composite_road(tungasletta,[],tungasletta).
composite_road(tunga,[street],tunga_street).
composite_road(tun,[street],tun_street).
composite_road(turist,[street],turist_street).
composite_road(tverrstien,[],tverrstien).
composite_road(tvetestien,[],tvetestien).
composite_road(tyholt,[alle],tyholt_alle).
composite_road(tyholt,[street],tyholt_street).
composite_road(tyras,[street],tyras_street).
composite_road(tyrihans,[street],tyrihans_street).
composite_road(tyrkrisveita,[],tyrkrisveita).
composite_road(tømmerlunna,[],tømmerlunna).
composite_road(udbyes,[street],udbyes_street).
composite_road(uglagjerdet,[],uglagjerdet).
composite_road(uglahaugstien,[],uglahaugstien).
composite_road(uglamarkstien,[],uglamarkstien).
composite_road(ugla,[street],ugla_street).
composite_road(ullins,[street],ullins_street).
composite_road(ulstadløkk,[street],ulstadløkk_street).
composite_road(underhaugs,[street],underhaugs_street).
composite_road(urds,[street],urds_street).
composite_road(uståsen,[],uståsen).
composite_road(utleirmark,[],utleirmark).
composite_road(utleirtunet,[],utleirtunet).
composite_road(utleir,[street],utleir_street).
composite_road(utsikten,[alle],utsikten_alle).
composite_road(valentinlyst,[street],valentinlyst_street).
composite_road(valgrind,[street],valgrind_street).
composite_road(valkendorfs,[street],valkendorfs_street).
composite_road(valkyrje,[street],valkyrje_street).
composite_road(valsetsvingen,[],valsetsvingen).
composite_road(valøyslyngen,[],valøyslyngen).
composite_road(valøy,[street],valøy_street).
composite_road(vanadis,[street],vanadis_street).
composite_road(vangslunds,[street],vangslunds_street).
composite_road(varde,[street],varde_street).
composite_road(vaterlandsveita,[],vaterlandsveita).
composite_road(vegamot,[],vegamot).
composite_road(vegmesterstien,[],vegmesterstien).
composite_road(veimester,[kroghs,street],veimester_kroghs_street).
composite_road(veimester,[kroghs_street],veimester_kroghs_street).
composite_road(veisletten,[alle],veisletten_alle).
composite_road(venus,[street],venus_street).
composite_road(verfts,[street],verfts_street).
composite_road(vestmark,[street],vestmark_street).
composite_road(vestre,[hallsetvangen],vestre_hallsetvangen).
composite_road(vestre,[husebytun],vestre_husebytun).
composite_road(vestre,[kanalkai],vestre_kanalkai).
composite_road(vestre,[moholttun],vestre_moholttun).
composite_road(vestre,[rosten],vestre_rosten).
composite_road(vestre,[tunhøgda],vestre_tunhøgda).
composite_road(vetle,[vislies,street],vetle_vislies_street).
composite_road(vetle,[vislies_street],vetle_vislies_street).
composite_road(victor,[ronanders,street],victor_ronanders_street).
composite_road(victor,[ronanders_street],victor_ronanders_street).
composite_road(victoria,[bachkes,street],victoria_bachkes_street).
composite_road(victoria,[bachkes_street],victoria_bachkes_street).
composite_road(vidarheims,[street],vidarheims_street).
composite_road(vika,[street],vika_street).
composite_road(vikelvfaret,[],vikelvfaret).
composite_road(viktor,[baumanns,street],viktor_baumanns_street).
composite_road(viktor,[baumanns_street],viktor_baumanns_street).
composite_road(vikåsen,[],vikåsen).
composite_road(vilhelm,[krags,street],vilhelm_krags_street).
composite_road(vilhelm,[krags_street],vilhelm_krags_street).
composite_road(vilhelm,[storms,street],vilhelm_storms_street).
composite_road(vilhelm,[storms_street],vilhelm_storms_street).
composite_road(vinkelstien,[],vinkelstien).
composite_road(vinter,[street],vinter_street).
composite_road(vipe,[street],vipe_street).
composite_road(vognhall,[street],vognhall_street).
composite_road(vold,[street],vold_street).
composite_road(vollabakken,[],vollabakken).
composite_road(vollafallet,[],vollafallet).
composite_road(volve,[street],volve_street).
composite_road(vorp,[plassen],vorp_plassen).
composite_road(vorsetlia,[],vorsetlia).
composite_road(være,[vestre],være_vestre).
composite_road(værestien,[],værestien).

%% composite_road(væretrøa,[],væretrøa). %% unnec, Værestrøa %% TA-080911

composite_road(vådanstien,[],vådanstien).
composite_road(vådan,[street],vådan_street).
composite_road(vår,[frue,strete],vår_frue_strete).
composite_road(vår,[frues,street],vår_frues_street).
composite_road(vår,[frues_street],vår_frues_street).
composite_road(waldemar,[aunes,street],waldemar_aunes_street).
composite_road(waldemar,[aunes_street],waldemar_aunes_street).
composite_road(walldens,[street],walldens_street).
composite_road(wedels,[street],wedels_street).
composite_road(weidemanns,[street],weidemanns_street).
composite_road(wessels,[street],wessels_street).
composite_road(westermannsveita,[],westermannsveita).
composite_road(wilhelmsmyr,[street],wilhelmsmyr_street).
composite_road(william,[farres,street],william_farres_street).
composite_road(william,[farres_street],william_farres_street).
composite_road(willmannsveita,[],willmannsveita).
composite_road(wincklers,[street],wincklers_street).
composite_road(yggdrasil,[street],yggdrasil_street).
composite_road(yrkesskole,[street],yrkesskole_street).
composite_road(ørjaveita,[],ørjaveita).
composite_road(østerli,[street],østerli_street).
composite_road(østersunds,[street],østersunds_street).
composite_road(østkoll,[street],østkoll_street).
composite_road(østmark,[street],østmark_street).
composite_road(østmo,[street],østmo_street).
composite_road(østre,[berg],østre_berg).
composite_road(østre,[hallsetvangen],østre_hallsetvangen).
composite_road(østre,[ila],østre_ila).
composite_road(østre,[moholttun],østre_moholttun).
composite_road(østre,[rosten],østre_rosten).
composite_road(østre,[tunhøgda],østre_tunhøgda).
composite_road(østtun,[street],østtun_street).
composite_road(øverfoss,[street],øverfoss_street).
composite_road(øvergeilan,[],øvergeilan).
composite_road(øvergjerdet,[],øvergjerdet).
composite_road(øvertrøa,[],øvertrøa).
composite_road(øvre,[bakklandet],øvre_bakklandet).
composite_road(øvre,[bergsvingen],øvre_bergsvingen).
composite_road(øvre,[ferstad,street],øvre_ferstad_street).
composite_road(øvre,[ferstad_street],øvre_ferstad_street).
composite_road(øvre,[flatås,street],øvre_flatås_street).
composite_road(øvre,[flatås_street],øvre_flatås_street).
composite_road(øvre,[grilstadkleiva],øvre_grilstadkleiva).
composite_road(øvre,[kristianstens,street],øvre_kristianstens_street).
composite_road(øvre,[kristianstens_street],øvre_kristianstens_street).
composite_road(øvre,[kvåls,street],øvre_kvåls_street).
composite_road(øvre,[kvåls_street],øvre_kvåls_street).
composite_road(øvre,[marienlyst],øvre_marienlyst).
composite_road(øvre,[møllenberg,street],øvre_møllenberg_street).
composite_road(øvre,[møllenberg_street],øvre_møllenberg_street).
composite_road(øvre,[sjetnhaugan],øvre_sjetnhaugan).
composite_road(øvre,[sverresborg],øvre_sverresborg).
composite_road(øvre,[tvereggen],øvre_tvereggen).
composite_road(øvre,[alle],øvre_alle).
composite_road(øystein,[langsets,street],øystein_langsets_street).
composite_road(øystein,[langsets_street],øystein_langsets_street).
composite_road(øystein,[møylas,street],øystein_møylas_street).
composite_road(øystein,[møylas_street],øystein_møylas_street).
composite_road(øysteins,[street],øysteins_street).
composite_road(åker,[street],åker_street).
composite_road(åsbakken,[],åsbakken).
composite_road(åsheim,[street],åsheim_street).
composite_road(åsvang,[street],åsvang_street).
composite_road(røstadbakken,[],røstadbakken).
