/* -*- Mode:Prolog; coding:utf-8; -*- */
%% Generated by class regtopToBusTUC.TopRegUpdate on 2014-06-19 16:21:27.78

% Xmas routes before winter routes
% Easter routes before winter routes

%% Route module 'nil' in route_period means that the route module is not implemented yet
%% Important to have dummy route modules to give message of no routes for this date

%%%% ACTUAL  ROUTES              START-DATE           END-DATE (sorted!)

%%route_period( tt, r1618_110517, date(2011,05,17),   date(2011,05,17) ). 
%%route_period( tt, r1611_100823, date(2010,08,23),   date(2011,06,26) ).
%%route_period( tt, r1603_120409, date(2012,04,09),   date(2012,05,12) ). %% Overwrote 120415
%%route_period( tt, r1601_120415, date(2012,04,15),   date(2012,06,24) ).
%%route_period( tt, r1602_120425, date(2012,04,25),   date(2012,06,24) ). %% Mangler alle linjer over 79
%%route_period( tt, r1611_110627, date(2012,06,27),   date(2012,08,14) ).     
%%route_period( tt, r1602_120813, date(2012,08,13),   date(2012,09,12) ).
%%route_period( tt, r1612_121001, date(2012,10,01),   date(2012,11,30) ).  %% New nightbusses etc. ver5 Hoest 2012
%%route_period( tt, r1601_120101, date(2012,01,01),   date(2012,12,31) ).
%%route_period( tt, r1613_130622, date(2013,06,22),   date(2013,08,11) ).     %% sommer2013
route_period(   tt, r1611_131201, date(2013,12,01),   date(2013,12,23) ).       %% NyttPrinsenkryss, vinter2013-2014?
route_period(   tt, r1611_140203, date(2014,02,03),   date(2014,03,30) ).       %% mars 2014
route_period(   tt, r1611_140517, date(2014,05,17),   date(2014,05,17) ).	%% 17mai
route_period(   tt, r1611_140331, date(2014,03,31),   date(2014,06,22) ).       %% Før og etter påske 2014
%%route_period( tt, r1613_130812, date(2013,08,12),   date(2014,06,22) ).     %% Vinter13_14
%%route_period( tt, r1601_130930, date(2013,09,30),   date(2014,07,22) ).       %% Høst2013oktober
route_period(   tt, r1611_140623, date(2014,06,23),   date(2014,08,17) ).	%% Sommerruter
route_period(   tmn,r1630_101201, date(2012,12,01),   date(2014,12,31) ).
route_period(   gb, r1630_111201, date(2012,12,01),   date(2014,12,31) ).  %% Graakallbanen
route_period(   tt, r1605_140102, date(2014,01,02),   date(2015,01,01) ).       %% 2014v1, %% NyttPrinsenkryss, vinter2013-2014
