/* -*- Mode:Prolog; coding:utf-8; -*- */
%% Generated by regtopToBusTUC.TopRegUpdate.java on 2012-12-17 12:18:20.673

% Xmas routes before winter routes
% Easter routes before winter routes

%% Route module 'nil' in route_period means that the route module is not implemented yet
%% Important to have dummy route modules to give message of no routes for this date

%%%% ACTUAL  ROUTES              START-DATE           END-DATE (sorted!)

%%route_period( tt, r1618_110517, date(2011,05,17),   date(2011,05,17) ).       
%%route_period( tt, r1611_100823, date(2010,08,23),   date(2011,06,26) ).
route_period(   tmn,r1630_101201, date(2011,12,01),   date(2011,12,31) ).
route_period(   tt, r1602_120401, date(2012,04,01),   date(2012,04,08) ).
%%route_period( tt, r1603_120409, date(2012,04,09),   date(2012,05,12) ). %% Overwrote 120415
route_period(   tt, r1602_120517, date(2012,05,17),   date(2012,05,17) ).
%%route_period( tt, r1601_120415, date(2012,04,15),   date(2012,06,24) ).
%%route_period( tt, r1602_120425, date(2012,04,25),   date(2012,06,24) ). %% Mangler alle linjer over 79
route_period(   tt, r1604_120625, date(2012,06,25),   date(2012,08,12) ).
%%route_period( tt, r1611_110627, date(2012,06,27),   date(2012,08,14) ).     
%%route_period( tt, r1602_120813, date(2012,08,13),   date(2012,09,12) ).
route_period(   tt, r1612_121001, date(2012,10,01),   date(2012,11,30) ).  %% New nightbusses etc. ver5 Høst
route_period(   tt, r1612_121224, date(2012,12,24),   date(2012,12,24) ).	%% Julaften 2012
route_period(   tt, r1613_121225, date(2012,12,25),   date(2012,12,28) ).       %% Mellomjula
route_period(   tt, r1611_121201, date(2012,12,01),   date(2012,12,30) ).       %% Vinter 2012
route_period(   tt, r1614_121224, date(2012,12,24),   date(2012,12,31) ).       %% Nyttårsaften
route_period(   tt, r1613_121225, date(2012,12,25),   date(2013,01,01) ).       %% Mellomjula
%%route_period(   tt, r1612_121024, date(2012,10,24),   date(2013,03,24) ).  %% ny veil. Høst 2012
route_period(   tt, r1611_121201, date(2012,12,01),   date(2013,06,23) ).       %% Vinter 2012
%%route_period(   tt, r1601_120101, date(2012,01,01),   date(2012,12,31) ).
route_period(   gb, r1630_111201, date(2011,12,01),   date(2012,12,31) ).  %% Gråkallbanen
