/* -*- Mode:Prolog; coding:utf-8; -*- */
%% Generated by regtopToBusTUC.TopRegUpdate.java on 2013-06-24 10:19:25.74

% Xmas routes before winter routes
% Easter routes before winter routes

%% Route module 'nil' in route_period means that the route module is not implemented yet
%% Important to have dummy route modules to give message of no routes for this date

%%%% ACTUAL  ROUTES              START-DATE           END-DATE (sorted!)

%%route_period( tt, r1618_110517, date(2011,05,17),   date(2011,05,17) ). 
%%route_period( tt, r1611_100823, date(2010,08,23),   date(2011,06,26) ).
route_period(   tmn,r1630_101201, date(2012,12,01),   date(2014,12,31) ).
%%route_period( tt, r1603_120409, date(2012,04,09),   date(2012,05,12) ). %% Overwrote 120415
%%route_period( tt, r1601_120415, date(2012,04,15),   date(2012,06,24) ).
%%route_period( tt, r1602_120425, date(2012,04,25),   date(2012,06,24) ). %% Mangler alle linjer over 79
%%route_period( tt, r1611_110627, date(2012,06,27),   date(2012,08,14) ).     
%%route_period( tt, r1602_120813, date(2012,08,13),   date(2012,09,12) ).
%%route_period( tt, r1612_121001, date(2012,10,01),   date(2012,11,30) ).  %% New nightbusses etc. ver5 Hoest 2012
route_period(   tt, r1612_121224, date(2012,12,24),   date(2012,12,24) ).  %% Julaften      2012.12.24
route_period(   tt, r1614_121227, date(2012,12,27),   date(2012,12,27) ).  %% Mellomjula27  2012.12.27
route_period(   tt, r1613_121225, date(2012,12,25),   date(2012,12,28) ).  %% Mellomjula    2012.12.25-26 og 28 (og 1/1)
route_period(   tt, r1611_121201, date(2012,12,01),   date(2012,12,30) ).  %% Vinter 2012   2012.12.29-30 (og fra 2/1)
%%route_period( tt, r1601_120101, date(2012,01,01),   date(2012,12,31) ).
route_period(   tt, r1615_121224, date(2012,12,24),   date(2012,12,31) ).  %% Nyttaarsaften  2012.12.31
route_period(   tt, r1613_121225, date(2012,12,25),   date(2013,01,01) ).  %% Mellomjula   (2012.12.25-26 og 28) og 1/1
route_period(   tt, r1602_130326, date(2013,03,26),   date(2013,04,01) ).	%% vaar2013
route_period(   tt, r1603_130402, date(2013,04,02),   date(2013,04,14) ).	%% vaar2013
route_period(   tt, r1601_130306, date(2013,03,06),   date(2013,04,14) ).	%% vaar2013
route_period(   tt, r1611_130429, date(2013,04,29),   date(2013,04,30) ).       %% V��r2013
route_period(   tt, r1612_130429, date(2013,04,29),   date(2013,05,01) ).	%% MaiHelligdager
route_period(   tt, r1611_130429, date(2013,04,29),   date(2013,05,08) ).       %% V��r2013
route_period(   tt, r1612_130429, date(2013,04,29),   date(2013,05,09) ).	%% MaiHelligdager
route_period(   tt, r1611_130429, date(2013,04,29),   date(2013,05,16) ).       %% V��r2013
route_period(   tt, r1613_130429, date(2013,04,29),   date(2013,05,17) ).	%% 17mai
route_period(   tt, r1611_130429, date(2013,04,29),   date(2013,05,19) ).       %% V��r2013
route_period(   tt, r1612_130429, date(2013,04,29),   date(2013,05,20) ).	%% MaiHelligdager

route_period(   tt, r1611_130429, date(2013,04,29),   date(2013,06,23) ).       %% Vå2013
route_period(   tt, r1613_130622, date(2013,06,22),   date(2013,08,11) ).	%% sommer2013
%Feil route_period(   tt, r1612_130617, date(2013,06,17),   date(2013,08,11) ).       %% sommer13
route_period(   tt, r1611_130429, date(2013,04,29),   date(2014,05,23) ).	%% Vår 2013

route_period(   gb, r1630_111201, date(2012,12,01),   date(2014,12,31) ).  %% Graakallbanen
