%% Generated by regtopToBusTUC.RegpasHolder.java on 2012-01-20 13:47:12.497

%% PASSES4 (TOURTYPE, STATION_NR, STATION, SEQ_NR, ARR_DELAY, DEP_DELAY)
%%    Example: passes4(17326,16011035,anton_grevskotts_vei,22,15,16).

%% NTOURSTOPS (TOURTYPE,LENGTH). Tourtype almost matches the linenumber in regpas.pl and FILE.TDA or FILE.TMS
%%    Defines the length (number of stations) inthe tourtype, e.g. ntourstops(12713,5).


%% PASSES4 (TOURTYPE, STATION NUMBER, STATION, SEQNUMBER, ARR DELAY, DEP DELAY)
passes4(1,16010719,dronningensgt,1,0,0).
passes4(1,16010724,hospitalkirka,2,1,1).
passes4(1,16010779,kalvskinnet,3,2,2).
passes4(1,16010715,skansen,4,3,3).
passes4(1,16010792,ila,5,4,4).
passes4(1,16010713,bergsli_gate,6,5,5).
passes4(1,16010712,nyveibakken_trondheim,7,6,6).
passes4(1,16010711,bygrensen,8,7,7).
passes4(1,16010740,belvedere,9,8,8).
passes4(1,16019999,breidablikk,10,9,9).
passes4(1,16010709,nordre_hoem,11,10,10).
passes4(1,16010708,søndre_hoem,12,11,11).
passes4(1,16010707,rognheim,13,13,13).
passes4(1,16010706,munkvoll_trikk,14,15,15).
passes4(1,16010705,ferstad,15,16,16).
passes4(1,16010704,ugla_trondheim,16,17,17).
passes4(1,16010703,kyvannet,17,18,18).
passes4(1,16010702,vestmarka,18,19,19).
passes4(1,16010701,herlofsenløypa,19,20,20).
passes4(1,16010700,lian_trondheim,20,21,999).
passes4(1,16010700,lian_trondheim,21,999,0).
passes4(22,16010701,herlofsenløypa,1,1,1).
passes4(22,16011702,vestmarka,2,2,2).
passes4(22,16010703,kyvannet,3,4,4).
passes4(22,16011704,ugla_trondheim,4,5,5).
passes4(22,16010705,ferstad,5,6,6).
passes4(22,16010706,munkvoll_trikk,6,8,8).
passes4(22,16010707,rognheim,7,9,9).
passes4(22,16011708,søndre_hoem,8,10,10).
passes4(22,16010709,nordre_hoem,9,11,11).
passes4(22,16019999,breidablikk,10,13,13).
passes4(22,16010740,belvedere,11,14,14).
passes4(22,16010711,bygrensen,12,15,15).
passes4(22,16010712,nyveibakken_trondheim,13,16,16).
passes4(22,16011792,ila,14,17,17).
passes4(22,16011715,skansen,15,18,18).
passes4(22,16011779,kalvskinnet,16,19,19).
passes4(22,16011724,hospitalkirka,17,20,20).
passes4(22,16010718,st_olavs_gt,18,21,999).
ntourstops(1,21).
ntourstops(22,18).
