/* -*- Mode:Prolog; coding:utf-8; -*- */
%% Generated by regtopToBusTUC.VersionUpdate.java on 2015-08-14 18:39:30.355
%% FILE version.pl
%% SYSTEM TUC
%% CREATED TA-970913
/* REVISED : RS- */  version_date('AtB-I  Date 150814  Høst').

%% Høst
