/* -*- Mode:Prolog; coding:utf-8; -*- */
%% Generated by regtopToBusTUC.VersionUpdate.java on 2013-06-21 14:01:54.614
%% FILE version.pl
%% SYSTEM TUC
%% CREATED TA-970913
/* REVISED : RS- */  version_date('AtB-I  Date 130621').
%% sommer13
