/* -*- Mode:Prolog; coding:utf-8; -*- */
%% Generated by regtopToBusTUC.VersionUpdate.java on 2013-06-24 10:19:26.016
%% FILE version.pl
%% SYSTEM TUC
%% CREATED TA-970913
/* REVISED : RS- */  version_date('AtB-M  Date 130627').

%% sommer2013