/* -*- Mode:Prolog; coding:utf-8; -*- */
%% Generated by class regtopToBusTUC.TopRegUpdate on 2019-01-04 12:32:24.302

:- module( route_period, [ route_period/4 ] ).

% Xmas routes before winter routes
% Easter routes before winter routes

%% Route module 'nil' in route_period means that the route module is not implemented yet
%% Important to have dummy route modules to give message of no routes for this date

%%%% ACTUAL  ROUTES              START-DATE           END-DATE (sorted!)

route_period(   tt, r160_200621, date(2020,4,28),   date(2020,8,9) ).       %% Sommer 2020 TEST
