/* -*- Mode:Prolog; coding:utf-8; -*- */
%% Generated by class UpdateRoutePeriode on 2020-09-27 03:03:30.918

:- module( route_period, [ route_period/4 ] ).

% Xmas routes before winter routes
% Easter routes before winter routes

%% Route module 'nil' in route_period means that the route module is not implemented yet
%% Important to have dummy route modules to give message of no routes for this date

%%%% ACTUAL  ROUTES              START-DATE           END-DATE (sorted!)

route_period(   tt, r160_200622, date(2020,06,22),   date(2020,08,14) ).    %% Auto Update: 2020-07-28
route_period(   tt, r160_200810, date(2020,08,10),   date(2021,07,01) ).    %% Auto Update: 2020-09-25
route_period(   tt, r160_200810, date(2020,08,10),   date(2021,07,02) ).    %% Auto Update: 2020-09-27
route_period(   tt, r160_200622, date(2020,06,22),   date(2021,07,02) ).    %% Auto Update: 2020-08-11
