/* -*- Mode:Prolog; coding:utf-8; -*- */
%% Generated by class regtopToBusTUC.TopRegUpdate on 2015-10-04 14:09:03.772

:- module( route_period, [ route_period/4 ] ).

% Xmas routes before winter routes
% Easter routes before winter routes

%% Route module 'nil' in route_period means that the route module is not implemented yet
%% Important to have dummy route modules to give message of no routes for this date

%%%% ACTUAL  ROUTES              START-DATE           END-DATE (sorted!)

%%route_period( tt, r1618_110517, date(2011,05,17),   date(2011,05,17) ). 
%%route_period( tt, r1611_100823, date(2010,08,23),   date(2011,06,26) ).
%%route_period( tt, r1603_120409, date(2012,04,09),   date(2012,05,12) ). %% Overwrote 120415
%%route_period( tt, r1601_120415, date(2012,04,15),   date(2012,06,24) ).
%%route_period( tt, r1602_120425, date(2012,04,25),   date(2012,06,24) ). %% Mangler alle linjer over 79
%%route_period( tt, r1611_110627, date(2012,06,27),   date(2012,08,14) ).     
%%route_period( tt, r1602_120813, date(2012,08,13),   date(2012,09,12) ).
%%route_period( tt, r1612_121001, date(2012,10,01),   date(2012,11,30) ).  %% New nightbusses etc. ver5 Hoest 2012
%%route_period( tt, r1601_120101, date(2012,01,01),   date(2012,12,31) ).
%%route_period( tt, r1613_130622, date(2013,06,22),   date(2013,08,11) ).     %% sommer2013
%%route_period( tt, r1613_130812, date(2013,08,12),   date(2014,06,22) ).     %% Vinter13_14
%%route_period( tt, r1601_130930, date(2013,09,30),   date(2014,07,22) ).       %% Høst2013oktober
route_period(   tt, r1603_151012, date(2015,10,12),   date(2015,12,23) ).	%% Høst15
route_period(   tt, r1602_150901, date(2015,09,01),   date(2015,12,23) ).	%% Høst v3
