/* -*- Mode:Prolog; coding:utf-8; -*- */
%% FILE topreg.pl
%% SYSTEM BussTUC DOMAIN TT
%% CREATED TA-981231
%% REVISED TA-120402
%% REVISED RS-121024

%% Contains the important information about route modules. Loaded from interfaceroutes.pl module
%% RS-131223    Included in / Exported throug   busroute.pl
:-module('topreg', [ compilerouteaux/2, default_message/3, default_period/3, period_message/2, routedomain/1 ] ). % , route_period/4

% See compileroute.pl for compilation

% See busdat.pl for specialday to day mapping

%% Ny linje
%:-use_module( 'route_period', [ route_period/4 ] ).



%%%%%%%%%% THIS TABLE IS CRUCIAL %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% route_period must be sorted according to their end date        %

%%% SEE ALSO busdat.pl for special dates !!!!!!!!!!!!!!!!!!!!!! %%
%%% Update period_message and  default_period !!!               %%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%% Route Domains %%

routedomain(tt).  %% Team Trafikk
routedomain(gb).  %% Gråkallbanen
routedomain(fb).  %% Flybussen
routedomain(tmn). %% Generic for TMN related routes


%% TT (Team Trafikk) %%%%%%%

%% Special list to be compiled

compilerouteaux( tt, [
%%      'db/regbusall', %% Inclusive  set of buses      %% RS-131226 Removed?
        'db/regstr',    %% Streets
        'db/regcompstr' %% Composite Street names
]).

%% DEFAULT ROUTE PERIODS

%default_period(tt,winter, r1601_110822).  %% 2011 Autumn
default_period( tt, winter, r1601_130930).  %% 2014 Winter/Spring?
default_period( tt, summer, r1611_140623).  %% 2013 Summer
default_period(tt,previous, r1611_140203).  %% 2013 Most recently period used %% RS-140616


%default_message(tt,winter,['AtB winter routes are from  Jan. 2, 2012  to Jun. 26, 2012.',
%                           'AtB vinterruter gjelder fra 2. jan. 2012 til 26. jun. 2012']).
%
default_message(tt,winter,['AtB winter routes are from  Aug. 13 to Dec 23.  2014.',
                           'AtB vinterruter gjelder fra 13. aug. til 23. des. 2014']).

default_message(tt,summer,['AtB summer routes are from Jun. 23 to  Aug. 17. 2014',
                           'AtB sommerruter gjelder fra 24. juni til 11. aug. 2014.']).

%% ACTUAL ROUTE PERIODS  SORTED ON --- END DATE ----
%%see routes.pl


%Lørdagsruter med første avgang fra kl 08.30 med tilleggsturer.
period_message( r1611_140517,
[ 'AtB Routes for Constitution Day are as Saturday, starting from 8.30 o´clock',
  'AtB Lørdagsruter for 17. mai, med første avgang fra kl 08.30 og noen tilleggsturer']).

period_message( r1630_111201,
['AtB Routes for Tram 2012',
 'AtB Ruter for Trikk 2012']).

period_message( r1613_140415,
['AtB Routes for Easter 2014',
 'AtB Ruter påska 2014']).

period_message( r1614_140415,
['AtB Routes for Easter 2014',
 'AtB Ruter påska 2014']).

period_message( r1615_140415,
['AtB Routes for Easter 2014',
 'AtB Ruter påska 2014']).

period_message( r1611_140623,
['AtB Routes for summer 2014',
 'AtB Sommerruter  2014']).

period_message( r1611_140818,
['AtB Autumn routes',
 'AtB Høstruter']). %% \+ .   %% RS-120810

%period_message( r1611_141020,
%['End of Daylight Saving Time!',
% 'Husk Vintertid!']). %% \+ .   %% RS-120810

period_message( r1601_120101,
['AtB Winter routes',
 'AtB Vinterruter']). %% \+ .   %% RS-111220


period_message( r1611_131201,
['AtB Winter routes',
 'AtB Vinterruter']). %% \+ .   %% RS-121223


%period_message( r1611_141201,
%['Normal Routes',               %% RS-141207.
% 'Vanlige Ruter']). %% \+ .   %% 01.12.14 – 23.12.14, 27.12.14 – 28.12.14 og 02.01.15 – 11.01.15

%period_message( r1612_141223,
%['Routes for Christmas Eve',
% 'Ruter for Julaften']). %% \+ .   %% RS-131223
period_message( r1612_141223,
['Routes for Christmas',
 'Ruter for Julen']). %% \+ .   %% RS-131223

%%%% 1-2.juledag, 6.juledag, nyttårsdag
period_message( r1613_141223,
['AtB 1st Christmas Day routes',
 'AtB Juleruter 1.juledag']). %% \+ .   %% RS-131223

period_message( r1614_131216,
['AtB Christmas (Saturday) routes for 27th',
 'Spesial/lørdags-ruter for 27/12']). %% \+ .   %% RS-131223

%%%% 4.5.juledag
period_message( r1614_141223,
['AtB Middle Christmas routes',
 'AtB Ruter for romjulen']). %% \+ .   %% RS-131223

period_message( r1615_141223,
['Routes for New Years Eve',
 'Ruter for Nyttårsaften']). %% \+ .   %% RS-131223

period_message( r1612_141223,
['Routes for New Years Day',
 'Ruter for Nyttårsdagen']). %% \+ .   %% RS-131223


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% RS-140616 This was moved to another file at some point: route_period.pl

/* -*- Mode:Prolog; coding:utf-8; -*- */
%% Generated by class regtopToBusTUC.TopRegUpdate on 2014-05-12 09:11:44.696

% Xmas routes before winter routes
% Easter routes before winter routes

%% Route module 'nil' in route_period means that the route module is not implemented yet
%% Important to have dummy route modules to give message of no routes for this date

%%%% ACTUAL  ROUTES              START-DATE           END-DATE (sorted!)

%%route_period( tt, r1618_110517, date(2011,05,17),   date(2011,05,17) ). 
%%route_period( tt, r1611_100823, date(2010,08,23),   date(2011,06,26) ).
%%route_period( tt, r1603_120409, date(2012,04,09),   date(2012,05,12) ). %% Overwrote 120415
%%route_period( tt, r1601_120415, date(2012,04,15),   date(2012,06,24) ).
%%route_period( tt, r1602_120425, date(2012,04,25),   date(2012,06,24) ). %% Mangler alle linjer over 79
%%route_period( tt, r1611_110627, date(2012,06,27),   date(2012,08,14) ).     
%%route_period( tt, r1602_120813, date(2012,08,13),   date(2012,09,12) ).
%%route_period( tt, r1612_121001, date(2012,10,01),   date(2012,11,30) ).  %% New nightbusses etc. ver5 Hoest 2012
%%route_period( tt, r1601_120101, date(2012,01,01),   date(2012,12,31) ).
%%route_period( tt, r1613_130622, date(2013,06,22),   date(2013,08,11) ).     %% sommer2013
%route_period(   tt, r1611_131201, date(2013,12,01),   date(2013,12,23) ).       %% NyttPrinsenkryss, vinter2013-2014?
%%route_period(   tt, r1612_131216, date(2013,12,16),   date(2013,12,24) ).       %% Julaften
%%route_period(   tt, r1613_131216, date(2013,12,16),   date(2013,12,26) ).       %% 1-2.juledag, 6.juledag, nyttårsdag
%%route_period(   tt, r1614_131216, date(2013,12,16),   date(2013,12,27) ).       %% 3.juledag
%%route_period(   tt, r1615_131216, date(2013,12,16),   date(2013,12,29) ).       %% 4.5.juledag
%%route_period(   tt, r1613_131216, date(2013,12,16),   date(2013,12,30) ).       %% 1-2.juledag, 6.juledag, nyttårsdag
%%route_period(   tt, r1616_131216, date(2013,12,16),   date(2013,12,31) ).       %% Nyttår
%%route_period(   tt, r1613_131216, date(2013,12,16),   date(2014,01,01) ).       %% 1-2.juledag, 6.juledag, nyttårsdag
%route_period(   tt, r1611_140203, date(2014,02,03),   date(2014,03,30) ).       %% mars 2014
%%route_period(   tt, r1613_140415, date(2014,04,15),   date(2014,04,15) ).       %% 15og21april
%%route_period(   tt, r1614_140415, date(2014,04,15),   date(2014,04,16) ).      %% 16april
%%route_period(   tt, r1615_140415, date(2014,04,15),   date(2014,04,20) ).      %% 17til20april
%%route_period(   tt, r1613_140415, date(2014,04,15),   date(2014,04,21) ).      %% 15og21april
%%route_period(   tt, r1611_140331, date(2014,03,31),   date(2014,05,16) ).       %% Før og etter påske 2014
%route_period(   tt, r1611_140517, date(2014,05,17),   date(2014,05,17) ).       %% 17mai
%route_period(   tt, r1611_140331, date(2014,03,31),   date(2014,06,22) ).       %% Før og etter påske 2014
%%%route_period( tt, r1613_130812, date(2013,08,12),   date(2014,06,22) ).     %% Vinter13_14
%%%route_period( tt, r1601_130930, date(2013,09,30),   date(2014,07,22) ).       %% Høst2013oktober
%route_period(   tmn,r1630_101201, date(2012,12,01),   date(2014,12,31) ).
%route_period(   gb, r1630_111201, date(2012,12,01),   date(2014,12,31) ).  %% Graakallbanen
%route_period(   tt, r1605_140102, date(2014,01,02),   date(2015,01,01) ).       %% 2014v1, %% NyttPrinsenkryss, vinter2013-2014
%%route_period(   tt, r1611_200203, date(2020,02,03),   date(2020,04,13) ).      %% Ruter med trikk

%%%%%% END OF ACTUAL ROUTE PERIODS %%%%%%%%%

