#!/bin/bash
cp -r ~/tele/REGTOP/$1  ~/tele/buster/db/tables/.
echo "compile_route_set($1), use_module( 'utility/extracut.pl', [ create_regcut/1 ] ), create_regcut($1), halt." | busstuc
create_busstuc


