/* -*- Mode:Prolog; coding:iso-8859-1; -*- */

/* -*- Mode:Prolog; coding:utf-8; -*- */
%% Comment generated by utility/extracut.pl æøå
:- use_module( regcut, [ composite_stat/3, cutloop_trace/3, cutloop_rid/7, departureday/4, dko/8, dkodate/2, ex_departureday/4, ex_ntourstops/2, ex_passes4/6,
                           hpl/4, ntourstops/2, passes4/6, regbus/1, route/3, xi/2 ] ).
%:-ensure_loaded( [ regbus, regcomp, regdep, regdko, reghpl, regpas ] ).
%%% 

test(X, A,B,C,D) :-
        X:hpl(A,B,C,D).

