/* -*- Mode:Prolog; coding:utf-8; -*- */
%% Generated by regtopToBusTUC.RegdepHolder.java on 2014-05-08 15:42:54.076

%% DEPARTUREDAY  ( RID, TOUR_TYPE, DEPARTURE_TIME, DAY_CODE )
%%   Example: departureday( bus_2_6101, 749, 723, 1).
%%   Tourtype almost matches the linenumber in regpas.pl and FILE.TDA or FILE.TMS

