/* -*- Mode:Prolog; coding:utf-8; -*- */
%% Generated by regtopToBusTUC.RegpasHolder.java on 2014-05-08 15:42:54.141

%% PASSES4 (TOURTYPE, STATION_NR, STATION, SEQ_NR, ARR_DELAY, DEP_DELAY)
%%    Example: passes4(17326,16011035,anton_grevskotts_vei,22,15,16).

%% NTOURSTOPS (TOURTYPE,LENGTH). Tourtype almost matches the linenumber in regpas.pl and FILE.TDA or FILE.TMS
%%    Defines the length (number of stations) inthe tourtype, e.g. ntourstops(12713,5).


%% PASSES4 (TOURTYPE, STATION NUMBER, STATION, SEQNUMBER, ARR DELAY, DEP DELAY)
